### ISSUE TITLE
Non-fatal Exception: com.google.firebase.e.c

### ISSUE THREAD

**Issue by max-makeichik** [firebase/quickstart-android#603] opened 2018-08-16 10:54 UTC
I get these exceptions from Crashlytics:

```
Non-fatal Exception: com.google.firebase.e.c  

| com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance (Unknown Source:34000)
-- | --
  | com.google.firebase.remoteconfig.zza.onResult (Unknown Source:1000)
  | com.google.android.gms.common.api.internal.BasePendingResult$CallbackHandler.handleMessage (Unknown Source)
  | android.os.Handler.dispatchMessage (Handler.java:102)
  | android.os.Looper.loop (Looper.java:154)
  | android.app.ActivityThread.main (ActivityThread.java:6776)
  | java.lang.reflect.Method.invoke (Method.java)
  | com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1496)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1386)


```
The initialization code 
```kotlin
val config: FirebaseRemoteConfig = FirebaseRemoteConfig.getInstance()
val settings = FirebaseRemoteConfigSettings.Builder().setDeveloperModeEnabled(isDevMode).build()
config.setConfigSettings(settings)
config.setDefaults(defaults)
suspendCancellableCoroutine { cont ->
                val config: FirebaseRemoteConfig = FirebaseRemoteConfig.getInstance()
                config.fetch(cacheDuration).addOnCompleteListener { res ->
                    val isSuccessful = res.isSuccessful
                    if (isSuccessful) {
                        config.activateFetched()
                    } else {
                        AppDelegate.instance.toolsConfig.exceptionLogger.logException(res.exception)
                    }

                    cont.resume(isSuccessful)
                }
}
```

```
implementation "com.google.firebase:firebase-config:$firebaseVersion"
implementation "com.google.android.gms:play-services-gcm:$googleServiceVersion"
implementation "com.google.firebase:firebase-core:$firebaseVersion"
firebaseVersion = '16.0.0'
googleServiceVersion = '15.0.1'
```

project build.gradle has 
`classpath 'com.google.gms:google-services:4.0.1'`
app build.gradle has 
`apply plugin: 'com.google.gms.google-services`

**Comment by samtstern** [comment] 2018-08-17 20:47
Hmm based on `Non-fatal Exception: com.google.firebase.e.c  ` it looks like this stack trace is proguarded which makes it pretty hard to debug.

Do you ever see this issue in a debug build?

**Comment by max-makeichik** [comment] 2018-08-20 09:54
Yes, it's in a debug build, this code is called in onStart, after super.onStart()

**Comment by max-makeichik** [comment] 2018-08-21 14:44
It's a floating bug, it appears not every time, when hiding/resuming app during initialization, but we don't know the exact way.

**Comment by samtstern** [comment] 2020-05-20 19:22
@max-makeichik since this bug is very old and we never found out how to reproduce it I am going to close the issue.  For future problems with the Crashlytics SDK please use the firebase-android-sdk repo.

**Closed by samtstern** 2020-05-20 19:22 UTC
Labels: api: remoteconfig
