### ISSUE TITLE
Topic not being created with FirebaseMessaging.getInstance().subscribeToTopic(...)

### ISSUE THREAD

**Issue by ThomasSunderland** [firebase/quickstart-android#61] opened 2016-06-23 13:52 UTC
Hello,

I am able to successfully send notifications to a single device and I am able to send them to a user segment, but in the Firebase Notifications console for my application for Target=Topic it shows "This project does not have any topics" even though I called FirebaseMessaging.getInstance().subscribeToTopic() from my Android application with several different topic names days ago.

The documentation for this is very sparse. Does this call not actually create a new topic? Is an HTTP call required to create the topic before the Android client can subscribe to it through this API?

If this API should indeed create the topic then how long does it take? I have been waiting almost 3 days now for it to appear in the console. I do not see any exceptions or errors generated on the client side when I make the call.

This was from a Samsung Galaxy S6 with Marshmallow.

Thanks,
Thomas

**Comment by samtstern** [comment] 2016-06-27 17:17
@ThomasSunderland it should create the topic and appear in the console within a few hours, so this is strange.  Can you confirm that you can send messages to the topic and receive them?  You can test this with the HTTP API by sending a request like this:

```
curl --header "Authorization: key=$API_KEY" \
       --header Content-Type:"application/json" \
       https://fcm.googleapis.com/fcm/send \
       -d "{ \"to\": \"/topics/foo\", \"notification\": { \"title\": \"Test\", \"text\": \"Hello World\" } }"
```

You can get your `$API_KEY` value from the `google-services.json` file.

**Comment by ThomasSunderland** [comment] 2016-06-27 18:05
@samtstern, I haven't run the test noted above yet, but I can say that I am able to run the sample app and create the "news" topic without any issues.

One thing that is different in the other app where the topics are not being created is that the actual topic creation is happening inside of an android library within my solution as opposed to within the main application. Do I need a separate google-services.json file for the library or should I maybe raise a create topic event from the library that the main application which already has the google-services.json file could handle?

**Comment by kroikie** [comment] 2016-06-28 19:51
I don't think you would need a separate google-services file for the library. As long as all of the necessary receivers are merged into the final AndroidManifest it should work as expected.

**Comment by ThomasSunderland** [comment] 2016-06-29 13:13
@kroikie Everything does appear to work as expected other than subscribing to new topics. The topics never appear in the Firebase console if the call is made from a library. I am, however, able to receive within the library notifications sent to a segment and to a single device without any issues.

**Comment by samtstern** [comment] 2016-06-30 20:12
@ThomasSunderland thanks for the details, I will take this report to the FCM team and see if there's any diagnostic issue you can provide that would help to debug.

**Comment by samtstern** [comment] 2016-07-06 21:48
@ThomasSunderland did your topics ever appear?  The FCM backend engineers found a few small bugs in the pipeline and fixed them, maybe that was affecting you.

**Comment by ThomasSunderland** [comment] 2016-07-11 14:50
@samtstern No, they never appeared

**Comment by romansmolyar** [comment] 2016-07-11 14:54
Hey all. Have same issue.

**Comment by kroikie** [comment] 2016-07-11 17:47
@ThomasSunderland Have you tried sending to the topic using the HTTP API? I'm trying to figure out where the issue is that the topic does not get created at all (in which case sending to HTTP should also fail) or if it is an issue of the Firebase console not displaying an existing topic.

**Comment by ThomasSunderland** [comment] 2016-07-12 13:14
@kroikie I get the following when I execute it through cURL:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   230    0   147  100    83     26     15  0:00:05  0:00:05 --:--:--   269<HTML>
<HEAD>
<TITLE>Unauthorized</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Unauthorized</H1>
<H2>Error 401</H2>
</BODY>
</HTML>

```

**Comment by ThomasSunderland** [comment] 2016-07-12 13:34
A couple of quick updates:

1. Executing through cURL worked fine if I use the server key rather than the API key

2. With that said this may no longer be an issue for me as I can see today the topics that I created yesterday from my Android display. Perhaps those changes that were mentioned earlier in the thread fixed my issue.

Thank you everyone for your help.

-Thomas Sunderland

**Comment by kroikie** [comment] 2016-07-12 22:47
@ThomasSunderland I'm very happy you got it working, I think you may have used the API key from the google-services.json file which is an Android API key, and a server API key is needed for sending FCM messages. If so you are not the only person that has made that error and we are updating our docs to make it clearer which API key you should use.

**Closed by kroikie** 2016-07-12 22:47 UTC

**Comment by jcampbell05** [comment] 2016-08-01 16:58
@kroikie  I am having issues, if I manually create a topic via the CURL I can send push notification messages to a topic even when they don't show up on the consoled.

The iOS Library doesn't seem to create this topic or let me push to it, nor do I get APNS.

**Comment by naasmobile** [comment] 2016-08-10 01:22
I am having a similar issue. I was able to successfully generate the message ID. I used FirebaseMessaging.getInstance().subscribeToTopic(InfoTopicName); to create the Topic in my java class. However, when trying to send  notification to the "topic", firebase claims no topics exists.  I used an HTTP curl request to generate the ID. How much time AFTER the ID is generated does it take firebase to create the topic?

**Comment by saleeh93** [comment] 2016-11-02 06:23
@samtstern I have a different issue, In my case device token is generated.And I have subscribed to a topic,everything works while I test it on debug version. When comes to release version device token is registered and I can send notification by device token,it works.But when I sent notification via topic it doesn't work. I can also send from firebase console to a platform. Topic is not even appeared in there, I don't know does anyone has this issue 
Thanks

**Comment by vedantswain** [comment] 2016-11-17 14:13
I have the same issue as @saleeh93 . How long does it take for a topic to appear on the console? When I did this earlier, it would happen instantaneously.

**Comment by saleeh93** [comment] 2016-11-17 16:26
@vedantswain It will take about 24 hrs to show up on firebase console, mean time you can try the curl to test

**Comment by WriteSongs** [comment] 2017-05-30 19:19
having the same issue when calling this via Android onClick
FirebaseMessaging.getInstance().subscribeToTopic(Config.TOPIC_NEWS);

**Comment by sterlingdiazd** [comment] 2017-11-16 03:26
This is what the documentation says:

`Pub/sub mechanism for sending notifications to subscribers. Learn more: Android, iOS. There is up to one day delay between new topic creation and when it becomes available as a target`
