### ISSUE TITLE
NullPointerException from FirebaseRemoteConfig.getInstance()

### ISSUE THREAD

**Issue by stari4ek** [firebase/quickstart-android#474] opened 2018-04-23 21:36 UTC
I'm seeing crashes in Crashlytics for most recent Firebase Remote Config (15.0.0)
Inside `Application.onCreate` `FirebaseRemoteConfig.getInstance` is called.

It produces crash:

```
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'void com.google.android.gms.internal.config.zzar.zzc(long)' on a null object reference
com.google.firebase.remoteconfig.FirebaseRemoteConfig. (Unknown Source)
com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance (Unknown Source)
com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance (Unknown Source)
==== app's part
by.stari4ek.config.ConfigFirebase. (ConfigFirebase.java:90)
```

Firebase version:
* `implementation "com.google.firebase:firebase-config:15.0.0"`
* `classpath 'com.google.gms:google-services:3.2.1'`

This is new issue introduced with 15.0.0. I didn't have it with previous versions

Devices (all are android tv):
* Xiaomi, Asus, Sony
* Android 5/6/7

**Comment by samtstern** [comment] 2018-04-23 21:48
I just took a look at the `15.0.0` proguard mapping:

```
com.google.firebase.remoteconfig.internal.Metadata -> com.google.android.gms.internal.config.zzar:
    // ...
    void setLastAppUpdateTime(long) -> zzc
```

I'll try to investigate more myself and then report this to the team.

**Comment by jkane001** [comment] 2018-04-24 00:49
FWIW, I'm getting the same crash after upgrading to 15.0.0

**Comment by samtstern** [comment] 2018-04-25 15:17
We've found the source of this error and will include a fix in an upcoming (likely the next) release.  I will update this thread whenever I get more information.

**Comment by swapnilgt** [comment] 2018-04-27 10:59
Is this already resolved?

**Comment by samtstern** [comment] 2018-04-27 15:14
@swapnilgt no, there has not been a release since `15.0.0` yet.

**Comment by jkane001** [comment] 2018-04-29 23:42
@samtstern Is there a workaround we can employ while we wait? This is (by far) my number 1 crash right now, by volume.

**Comment by ZebpayDipen** [comment] 2018-04-30 07:06
@samtstern  any update on this? As we are getting lots of many crashes due to this

**Comment by MohNage7** [comment] 2018-05-02 08:40
Any updates ? getting the same error on  **LG G4 Stylus Android 6**

**Comment by kozaxinan** [comment] 2018-05-03 08:04
There is a new version of Remote Config with version 15.0.2. I couldnt find any release note for it. Does this have fix for this issue?

**Comment by samtstern** [comment] 2018-05-03 21:26
Hi everyone, this should be fixed in version `15.0.2`.  Thank you all for reporting!

**Closed by samtstern** 2018-05-03 21:26 UTC

**Comment by saravanamoorthyk** [comment] 2019-06-18 12:54
Still, I'm facing this issue with firebase-config:17.0.0

`java.lang.RuntimeException: Unable to create application com.omly.customer.AppController.AppController: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.remoteconfig.FirebaseRemoteConfig com.google.firebase.remoteconfig.RemoteConfigComponent.get(java.lang.String)' on a null object reference`

Firebase version:

- implementation 'com.google.firebase:firebase-config:17.0.0'
- implementation 'com.google.firebase:firebase-core:16.0.9'

**Comment by kroikie** [comment] 2019-06-18 16:52
Hi @saravanamoorthyk I'm not sure this is the same issue. If your `getInstance` is failing it could be an issue with your Firebase configuration. If you create a new issue and provide some details on how you are using Remote Config in your case it will allow us to help a bit more.

**Comment by Mygod** [comment] 2019-07-24 04:17
Getting this error if direct boot is enabled. (everything is fine if it is outside of direct boot)

Source code: https://github.com/shadowsocks/shadowsocks-android

**Comment by arseniy899** [comment] 2019-07-24 12:12
I have also run into that issue, but on versions 16.4.1 and 18.0.0.


### Step 1: Describe your environment

  * Android device: Xiaomi Redmi 3S
  * Android OS version: 6.1
  * Google Play Services version: 17.7.85
  * Firebase/Play Services SDK version: 16.4.1, 18.0.0 (tried both of version with no success)
  
### Step 2: Describe the problem:
Initilizing Remote Config gives NullPointerException
#### Steps to reproduce:

  1. Init Firebase App
  2. Try to get instance of Remote Config
  
#### Observed Results:

  Instead of instance, got NPE:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.remoteconfig.FirebaseRemoteConfig com.google.firebase.remoteconfig.RemoteConfigComponent.get(java.lang.String)' on a null object reference
     at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(Unknown Source)
     at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(Unknown Source)

```
  
#### Expected Results:

  * I excpected to get instance to use Remote Config in the future
  
#### Relevant Code:
MyApp (init of Firebase App):
  ```
  public class MyApp extends Application
{
	@Override
	public void onCreate ()
	{
		super.onCreate();
		FirebaseApp.initializeApp(this);
	}

	@Override
	protected void attachBaseContext(Context base) {

		super.attachBaseContext(base);
		MultiDex.install(this);
		SplitCompat.install(this);
	}

}
```
LoginActivty (Launch activity):
```
public class LoginActivity extends ActivityCL //implements Thread.UncaughtExceptionHandler
{

	@Override
	@AddTrace(name = "LoginActivity.onCreate", enabled = true)
	protected void onCreate(Bundle savedInstanceState)
	{
		super.onCreate (savedInstanceState);
		FirebaseRemoteConfig remoteConfig = FirebaseRemoteConfig.getInstance();
	}
}
```
My app module gradle config:
```
apply plugin: 'com.android.application'
apply plugin: 'com.google.firebase.firebase-perf'
apply plugin: 'io.fabric'
apply plugin: 'com.google.gms.google-services'
android {
	compileSdkVersion 28
	useLibrary 'org.apache.http.legacy'
	packagingOptions {
		exclude 'META-INF/DEPENDENCIES'
		exclude 'META-INF/LICENSE'
		exclude 'META-INF/LICENSE.txt'
		exclude 'META-INF/license.txt'
		exclude 'META-INF/NOTICE'
		exclude 'META-INF/NOTICE.txt'
		exclude 'META-INF/notice.txt'
		exclude 'META-INF/androidsupportmultidexversion.txt'
		exclude 'androidsupportmultidexversion.txt'
		exclude 'META-INF/ASL2.0'
		exclude 'project.properties'
		exclude 'META-INF/INDEX.LIST'
	}
	lintOptions {
		checkReleaseBuilds false
		abortOnError false
	}

	defaultConfig {
		applicationId "********"
		minSdkVersion 18
		targetSdkVersion 28
		multiDexEnabled true
		versionCode ****
		versionName "***"
		vectorDrawables.useSupportLibrary true
		testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
	}
	configurations.all {
		resolutionStrategy.force 'com.google.code.findbugs:jsr305:3.0.1'
	}
	buildTypes {
		release {
			minifyEnabled true
			proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
			multiDexEnabled = true
		}
		debug {
			multiDexEnabled = true
			minifyEnabled = false
		}
	}
	compileOptions {
		sourceCompatibility JavaVersion.VERSION_1_7
		targetCompatibility JavaVersion.VERSION_1_7
	}
	dynamicFeatures = [":****", ":****"]
	dexOptions {
		preDexLibraries = true
	}

}
dependencies {
	implementation fileTree(include: ['*.jar'], dir: 'libs')

	repositories {
		maven { url "https://dl.bintray.com/hani-momanii/maven" }
		maven { url "https://github.com/omadahealth/omada-nexus/raw/master/release" }
		mavenCentral()
		google()
		jcenter()
		maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
		maven { url "https://s3.amazonaws.com/repo.commonsware.com" }
		maven { url "http://dl.bintray.com/waynejo/maven" }
		maven { url "https://jitpack.io" }
	}
	//...

	implementation 'com.google.android.gms:play-services-location:17.0.0'
	
	implementation 'com.google.firebase:firebase-core:17.0.1'
	implementation group: 'com.google.firebase', name: 'firebase-iid', version: '19.0.1'
	implementation 'com.google.firebase:firebase-messaging:19.0.1'
	implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'
	implementation 'com.google.firebase:firebase-perf:18.0.1'
	implementation 'com.google.firebase:firebase-config:16.4.1'

	implementation 'com.google.android.play:core:1.6.1'
	//...
	testImplementation 'junit:junit:4.12'
}
```

**Comment by kroikie** [comment] 2019-07-24 14:03
@arseniy899 could you try using the latest version of `firebase-config`?

**Comment by arseniy899** [comment] 2019-07-24 14:06
> 
> 
> @arseniy899 could you try using the [latest version](https://firebase.google.com/support/release-notes/android) of `firebase-config` right now it is `18.0.0`
@kroikie, I've already tried and mentioned it:
> Firebase/Play Services SDK version: 16.4.1, 18.0.0 (tried both of version with no success)

**Comment by kroikie** [comment] 2019-07-24 14:26
@arseniy899 sorry I missed that. The error seems to suggest that there is a `get(String)` being called. Is your issue that you are getting an NPE when getting a Remote Config instance, or are you getting the NPE when you are trying to get a String from Remote Config?

**Comment by arseniy899** [comment] 2019-07-24 14:32
Well, as in my example
`FirebaseRemoteConfig remoteConfig = FirebaseRemoteConfig.getInstance();`
all usage for now - only init (getting instance). 
Using AS sources look-up, NPE being thrown here:
```
public static FirebaseRemoteConfig getInstance(FirebaseApp var0) 
{
        return ((RemoteConfigComponent)var0.get(RemoteConfigComponent.class)).get("firebase");
}
```
So, calling it separately:
```
FirebaseApp app = FirebaseApp.initializeApp(context);
RemoteConfigComponent component = app.get(RemoteConfigComponent.class); // <- Component is NULL
if(component != null)
	FirebaseRemoteConfig remoteConfig = component.get("firebase");
```

**Comment by kroikie** [comment] 2019-07-24 14:34
@arseniy899 thanks for confirming, I'll investigate this further and report back here.

**Comment by arseniy899** [comment] 2019-07-25 07:32
> 
> 
> @arseniy899 thanks for confirming, I'll investigate this further and report back here.
Hello, thanks.
However, today I've noticed that Push-notification (FirebaseMessaging) also crashes with NPE:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.iid.FirebaseInstanceId.zza(java.lang.String)' on a null object reference
     at com.google.firebase.messaging.FirebaseMessaging.subscribeToTopic(com.google.firebase:firebase-messaging@@19.0.1:15)
```
With the following example:`FirebaseMessaging.getInstance ().subscribeToTopic ("updates");`
So, getInstance returns NULL. Please, help me as I've already tried everything.

**Comment by arseniy899** [comment] 2019-07-25 11:46
> 
> 
> @arseniy899 thanks for confirming, I'll investigate this further and report back here.

I've finally managed to launch the app without exception!
Exception occurs if in AndroidManifest.xml `tools:node="replace"` being set in `<application ...>` tag

**Comment by kroikie** [comment] 2019-07-25 13:41
@arseniy899 thanks for letting us know, glad you got the solution.

**Comment by passerbyloo** [comment] 2019-07-31 03:11
@arseniy899 i have the same issue with you, and the `firebase-config` version is `17.0.0`.
But i haven't `tools:node="replace"` in `AndroidManifest.xml`

**Comment by arseniy899** [comment] 2019-07-31 06:57
> @arseniy899 i have the same issue with you, and the `firebase-config` version is `17.0.0`.
> But i haven't `tools:node="replace"` in `AndroidManifest.xml`

Well, I've also have dynamic features in my app (ondemand). These modules require extending Application class with own one. Might be both of that affects. Do you have any modules in your project, especially dynamic features?

**Comment by passerbyloo** [comment] 2019-08-08 08:22
@arseniy899 i use react native for my project, it's hard to check whether those modules extending Application class.

**Comment by kroikie** [comment] 2019-08-08 15:51
@arseniy899 it may be worth filing an issue on the [React Native Firebase repo](https://github.com/invertase/react-native-firebase). If you have more details specific to the native SDK then please file a new issue here.

**Comment by agap** [comment] 2019-09-02 10:20
We're having similar issues after upgrade to 18.0.0, the project is in Java/Kotlin (there is no React Native stuff). I'll try to upgrade to 19.0.0 and post my findings here. If the issue will persist in 19.0.0, I'll file a new ticket.

**Comment by shah-nishant** [comment] 2019-12-09 19:35
We are also facing same issue after upgrading to 18.0.0. We are not using react native. Neither we have set tools:node="replace" in `<application ...>` tag

**Comment by shah-nishant** [comment] 2019-12-09 19:37
But it's only happening on Android 9 and Android 10 devices

**Comment by agap** [comment] 2019-12-09 19:42
The issue has disappeared after we upgraded to 19.0.0.

**Comment by arseniy899** [comment] 2019-12-09 19:46
> 
> 
> We are also facing same issue after upgrading to 18.0.0. We are not using react native. Neither we have set tools:node="replace" in `<application ...>` tag

Well, I haven't got access to Android 9 & 10 yet, so issue was connected not to android version, I think.
Maybe you can reopen issue?

**Comment by shah-nishant** [comment] 2019-12-09 20:08
We'll try 19.0.0 out. If it's not fixed. We'll reopen the issue.
Thanks everyone for the quick response

**Comment by abkoradiya** [comment] 2020-01-03 04:41
In 19.0.4, this issue still occurs.

**Comment by muditsen** [comment] 2020-02-03 07:23
I am also facing the same issue.

**Comment by mianaliasjad** [comment] 2020-03-03 05:34
still facing the same issue with com.google.firebase:firebase-config:19.1.1

**Comment by kjetile** [comment] 2020-03-18 15:27
I had the same issue with com.google.firebase:firebase-config:19.1.2. In my case the problem only happend on release builds with R8 enabled. I was able to get it to work by adding the following to my proguard-rules.pro:
`-keep class com.google.**`
`-keepclassmembers class com.google.**`

**Comment by cookiemouse** [comment] 2020-08-14 09:09
I'm getting the same crash In 19.2.0
please help me.
