### ISSUE TITLE
 Failed to initialize crash reporting

### ISSUE THREAD

**Issue by pesehr** [firebase/quickstart-android#483] opened 2018-04-30 06:09 UTC
HI,
I'm facing this type of issue.
Could you help me resolve the problem?

> `    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActivityManager.getMemoryInfo(android.app.ActivityManager$MemoryInfo)' on a null object reference
        at bgh.<init>(:com.google.android.gms.dynamite_dynamitemodulesc@12529020@12.5.29 (040308-192802242):29)
        at com.google.firebase.crash.internal.api.FirebaseCrashApiImpl.init(:com.google.android.gms.dynamite_dynamitemodulesc@12529020@12.5.29 (040308-192802242):12)
        at bfv.onTransact(:com.google.android.gms.dynamite_dynamitemodulesc@12529020@12.5.29 (040308-192802242):22)
        at android.os.Binder.transact(Binder.java:507)
        at com.google.android.gms.internal.measurement.zzn.transactAndReadExceptionReturnVoid(Unknown Source)
        at com.google.android.gms.internal.measurement.zzxa.zza(Unknown Source)
        at com.google.firebase.crash.zze.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
04-30 12:36:17.333 17645-17667/ir.ba24.key E/FirebaseCrash: Failed waiting for crash api to load.
    java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1036)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1327)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:249)
        at com.google.firebase.crash.FirebaseCrash.zzrl(Unknown Source)
        at com.google.firebase.crash.FirebaseCrash.zza(Unknown Source)
        at com.google.firebase.crash.zza.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)`

### Step 2: Describe your environment

  * Android device:  Samsung galaxy S6
  * Android OS version: 7.0
  * Google Play Services version:  com.google.gms:google-services:3.2.1
  * Firebase/Play Services SDK version: 15.0.0

**Comment by samtstern** [comment] 2018-04-30 18:05
@pesehr thanks for reporting this.  Can you reproduce this issue locally or is this something your users are seeing?  

Also can you confirm what version of Google Play services is installed on the Samsung Galaxy S6 device?

**Comment by pesehr** [comment] 2018-04-30 18:51
@samtstern thanks for your response.
Yes, I can reproduce it.
The version of Google play services on my device is: 12.5.29

**Comment by samtstern** [comment] 2018-04-30 18:52
@pesehr can you show the minimal amount of code needed to reproduce it on that device?

**Comment by samtstern** [comment] 2018-04-30 18:59
Ok so the sequence of events is:

1) See a crash
2) Launch the app again
3) Get this error in the logcat

Does this cause the app to crash or is this just reported in the logs?

**Comment by pesehr** [comment] 2018-04-30 19:00
this just reported in the logs.

**Comment by samtstern** [comment] 2018-04-30 19:07
@pesehr thank you, good to know it's not fatal.  We'll try to reproduce and then forward it on to the crash reporting engineering team.

By the way, you might want to consider moving to Crashlytics:
https://firebase.google.com/docs/crashlytics/upgrade-from-crash-reporting

It's the best option going forward and the migration is really simple.

**Comment by pesehr** [comment] 2018-04-30 19:14
@samtstern 
Actually, I use Crashlytics now but it doesn't report crashes so I thought maybe it's related to this error.

**Comment by samtstern** [comment] 2018-05-17 20:04
@pesehr I apologize for not responding, did you get Crashlytics to work?

**Comment by pesehr** [comment] 2018-05-17 20:47
@samtstern yes, that's my fault.
but I still get the reported error :(

**Comment by samtstern** [comment] 2018-05-17 20:59
Could you show your `dependencies` block for me?

**Comment by samtstern** [comment] 2018-11-13 16:39
@pesehr I hope you solved this problem!  Closing this issue because it's an old thread with no recent responses.  If you are still seeing this, please let me know and I will re-open it.

**Closed by samtstern** 2018-11-13 16:39 UTC

**Comment by kvenkatesh-nyros** [comment] 2018-12-14 04:58
i got same issue
