### ISSUE TITLE
 Waiting for the text  recognition model to be downloaded. Please wait

### ISSUE THREAD

**Issue by ayalma** [firebase/quickstart-android#784] opened 2019-01-13 12:45 UTC
* Android device:  Huawei nova plus 
  * Android OS version: Android 7.0 Api 24
  * Google Play Services version: 14.7.99(0400400-223214910)
  * Firebase/Play Services SDK version:
    All my dependency's
    // ML Kit dependencies
    implementation 'com.google.firebase:firebase-core:16.0.6'
    implementation 'com.google.firebase:firebase-ml-vision:18.0.2'
    implementation 'com.google.firebase:firebase-ml-vision-image-label-model:17.0.2'
    implementation 'com.google.firebase:firebase-ml-vision-face-model:17.0.2'
    implementation 'com.google.firebase:firebase-ml-model-interpreter:16.2.4'
    implementation 'org.tensorflow:tensorflow-lite:1.12.0'

   And  classpath 'com.google.gms:google-services:4.2.0'

 
### problem
  Text detection failed.com.google.firebase.ml.common.FirebaseMLException: Waiting for the text 
   recognition model to be downloaded. Please wait.

#### Steps to reproduce:
I just cloned your repo
#### Observed Results:

> 2019-01-13 15:45:53.429 32741-572/com.google.firebase.samples.apps.mlkit I/Vision: Loading library libocr.so
2019-01-13 15:45:53.429 32741-572/com.google.firebase.samples.apps.mlkit I/Vision: libocr.so library load status: false
2019-01-13 15:45:53.429 32741-572/com.google.firebase.samples.apps.mlkit W/TextNativeHandle: Native handle not yet available. Reverting to no-op handle.
2019-01-13 15:45:53.430 32741-572/com.google.firebase.samples.apps.mlkit W/DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite.text not found.
2019-01-13 15:45:53.435 32741-572/com.google.firebase.samples.apps.mlkit I/DynamiteModule: Considering local module com.google.android.gms.vision.dynamite.text:0 and remote module com.google.android.gms.vision.dynamite.text:0
2019-01-13 15:45:53.436 32741-572/com.google.firebase.samples.apps.mlkit W/DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite not found.
2019-01-13 15:45:53.440 32741-572/com.google.firebase.samples.apps.mlkit I/DynamiteModule: Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1800
2019-01-13 15:45:53.440 32741-572/com.google.firebase.samples.apps.mlkit I/DynamiteModule: Selected remote version of com.google.android.gms.vision.dynamite, version >= 1800
2019-01-13 15:45:53.444 32741-572/com.google.firebase.samples.apps.mlkit I/Vision: Loading library libocr.so
2019-01-13 15:45:53.444 32741-572/com.google.firebase.samples.apps.mlkit I/Vision: libocr.so library load status: false
2019-01-13 15:45:53.448 32741-32741/com.google.firebase.samples.apps.mlkit W/TextRecProc: Text detection failed.com.google.firebase.ml.common.FirebaseMLException: Waiting for the text recognition model to be downloaded. Please wait.

**Comment by the-dagger** [comment] 2019-01-22 20:02
@samtstern I think that this issues ties in with #586

**Comment by samtstern** [comment] 2019-01-24 17:39
@the-dagger I can confirm we're making some internal progress on #586, I've seen some good API proposals going around!

**Comment by the-dagger** [comment] 2019-01-24 18:39
Awesome, thanks!

**Comment by FarshidRoohi** [comment] 2019-01-29 08:58
I also have this problem.
there is a solution?

`
    implementation 'com.google.firebase:firebase-core:16.0.6'
`
`
    implementation 'com.google.firebase:firebase-ml-vision:18.0.2'
`

take image and call method
```
   mCamera.takePicture(null, null, new Camera.PictureCallback() {
     @Override
       public void onPictureTaken(byte[] bytes, Camera camera) {
              Bitmap bitmap = BitmapFactory.decodeByteArray(bytes, 0, bytes.length);
               ByteArrayOutputStream stream = new ByteArrayOutputStream();
               bitmap.compress(Bitmap.CompressFormat.JPEG, 1, stream);
               imageView.setImageBitmap(bitmap);
               fetch(bitmap);
     }
 });

```

```
 private void fetch(Bitmap bitmap) {
        final FirebaseVisionImage    firebaseVisionImage          = FirebaseVisionImage.fromBitmap(bitmap);
        FirebaseVisionTextRecognizer firebaseVisionTextRecognizer = FirebaseVision.getInstance().getOnDeviceTextRecognizer();

        firebaseVisionTextRecognizer.processImage(firebaseVisionImage)
                .addOnSuccessListener(new OnSuccessListener<FirebaseVisionText>() {
                    @Override
                    public void onSuccess(FirebaseVisionText firebaseVisionText) {
                        btn.setEnabled(true);
                        Log.i(TAG, "onFailure: " + firebaseVisionText.getText());

                    }
                }).addOnFailureListener(new OnFailureListener() {
            @Override
            public void onFailure(@NonNull Exception e) {
                btn.setEnabled(true);
                e.printStackTrace();
                Log.i(TAG, "onFailure: " + e.getMessage());
            }
        });
    }
```

**Comment by samtstern** [comment] 2019-02-07 05:20
There doesn't seem to be evidence here that anything is broken, models can sometimes take a long time to download on a slower or spottier connection.  Let's close this and I will update on when we have a better API for these downloads in #586.

**Closed by samtstern** 2019-02-07 05:20 UTC
Labels: mlkit

**Comment by GianfrancoMS** [comment] 2019-04-16 17:15
I have the same issue only on Huawei devices.

**Comment by hardysim** [comment] 2020-02-24 09:04
This pops up for me after trying on-device OCR on Android 11 DP 1.

On previous versions, everything worked fine (the models are also mentioned in the manifest to be downloaded via `com.google.firebase.ml.vision.DEPENDENCIES`).

But it seems that even with `FirebaseModelManager` I cannot check the status of *on-device* models (see firebase/firebase-android-sdk#47)?!

Is this a known problem with Android 11?

**Comment by shubh261096** [comment] 2020-02-27 12:01
Add this dependency. It worked for me.
`implementation 'com.google.firebase:firebase-ml-vision-barcode-model:16.0.2'`

**Comment by hardysim** [comment] 2020-02-27 12:24
This might be a workaround. But the auto-download will be fixed, right?

@shubh261096 which dependency do I need for OCR?

**Comment by kDmartel** [comment] 2020-03-20 10:50
Do you have a workaround? @samtstern samtstern

**Comment by JeetSA** [comment] 2020-10-09 06:38
I am having the same issue. Can anyone please help me?

**Comment by Anku5hk** [comment] 2021-02-04 15:56
> 
> 
> Add this dependency. It worked for me.
> `implementation 'com.google.firebase:firebase-ml-vision-barcode-model:16.0.2'`

Does not work, it shows duplicate classes when using mlkit's ocr. Anyone solved the issue?

**Comment by Anku5hk** [comment] 2021-02-04 16:02
The problem seems to be of play services version, on emulator it's not working but on physical device it is. Anyone having problem should check that one.

**Comment by hojat72elect** [comment] 2022-08-16 17:48
This problem isn't specific to emulators; it happens on "Samsung S20" and OnePlus devices as well. Does anyone has a solution?

**Comment by deniscoman** [comment] 2022-10-09 05:33
Still seeing this issue. Does anyone found any solution?

**Comment by MSchmidt** [comment] 2022-10-19 07:50
I'm seeing an increasing number of users that report broken OCR. For many it has started with a recent Android Update but I cannot reproduce it.

**Comment by jmazier-j2d** [comment] 2022-10-19 09:38
I'm experiencing this issue on many many recent Android devices (11 & 12)... The download just fail somehow, waiting is not an option (it just won't download).

**Comment by rodgomesc** [comment] 2022-10-28 17:39
how i fixed this,

### so far i found 3 scenarios so far that can cause this problem:
    1 - your android emulator is not a version that include google play services.
    2 - google play store need to be logged to be able to download the model
    3 - your google play services is not updated on emulator or physical devices
   
those steps solved for me

### 1 - updated google play services

<img width="600" src="https://user-images.githubusercontent.com/4893591/198697614-0b4fa727-ca75-4f39-9811-e2bc5f1b06dd.png"/>

### 2 - stop your app and clear all data and cache

<img src="https://user-images.githubusercontent.com/4893591/198698187-ba011774-f248-4b91-bae2-5fec84aa4906.png" />

### 3 - Signin in Google Play 

<img src="https://user-images.githubusercontent.com/4893591/198698549-dd95ec71-a24a-4ab8-823e-4494cf44ef7d.png" />

#### 4 - Open your App again!
