### ISSUE TITLE
Dynamic links not working on Firefox for Android

### ISSUE THREAD

**Issue by llDavidll** [firebase/quickstart-android#169] opened 2016-10-28 12:24 UTC
Hi,

I implemented dynamic links in my app, and I faced a problem when using them in the Firefox browser on Android.
Here is my environment :
- Android 5.0.1 and 5.0.2 (the two devices at my disposition).
- Google Play Services version : 9.8.77
- Firebase / Play Services SDK : 9.8.0
- Firefox browser version : 49.0.2

I tested with google chrome, the default Browser and even the "HtmlViewer" app of the two devices. When I use `AppInvite.AppInviteApi.getInvitation` with a result callback, `result.getStatus().isSuccess()` returns true and I can retrieve the link with `AppInviteReferral.getDeepLink(result.getInvitationIntent())` 

When I use Firefox, `result.getStatus()` returns `CANCELED` and every other fields are null (same as this issue https://github.com/firebase/quickstart-android/issues/38).
I tried calling `AppInviteReferral.hasReferral(activity.getIntent())`, but it returns false. I think it means the invitation id is somehow not sent by firefox when launching the Intent. The intent I receive in `activity.getIntent()` contains the link I want in the data, so I managed to make it work but this is more a workaround than a resolution of the issue. I also think it will not work if the app is not installed, because I will have no way of accessing the original intent.

I did some comparison between the intents I receive when it works and when it does not. When it works, the intent contains extras, something named `com.google.android.gms.appinvite.REFERRAL_BUNDLE`. With firefox, the intent extras are empty.

**Comment by llDavidll** [comment] 2016-10-28 12:43
While I'am on it, on Firefox my links opens a page with a "File not found" error. The app is launched (or the Play Store), but the user will see the error page when they return from the app. On other browsers I do not see this page. I don't think its related with my first issue, but it may help if this is not the normal behavior.

**Comment by samtstern** [comment] 2016-11-01 22:13
@llDavidll sounds like Firefox is stripping the extras before forwarding the link.  Thanks for the report, I will see if we can reproduce this and if so, what we can do about it.

**Comment by samtstern** [comment] 2017-06-28 15:30
It's been a long time since the last update here so I am going to close this issue.  Thank you for reporting it and feel free to re-open if it you'd like to discuss further.

**Comment by d-schmidt** [comment] 2017-11-06 21:20
@samtstern I can still reproduce this on my S7, Firefox 56
![screenshot_20171106-220519](https://user-images.githubusercontent.com/3226483/32464520-9a0af744-c340-11e7-8630-d141db09706e.png)

**Comment by samtstern** [comment] 2017-11-09 13:48
@d-schmidt nice!  Thanks for showing me.  Can you open the same link in Chrome and screenshot that?  Also do you have any extensions enabled in Firefox, and if so can you try removing them?

**Comment by d-schmidt** [comment] 2017-11-09 15:08
Chrome opens the Play Store or my App. When I click back there I'm on my original page where I put the link.

I don't have Firefox Addons.

**Comment by samtstern** [comment] 2017-11-10 11:52
@d-schmidt thanks for following up.  I sent this over to the dynamic links team to ask what information they need to debug.

**Comment by samtstern** [comment] 2017-11-10 22:40
@d-schmidt could you provide your user agent from Firefox on Android?  You can use a website like this one (or another) to get it:
https://www.whatismybrowser.com/detect/what-is-my-user-agent

**Comment by d-schmidt** [comment] 2017-11-19 18:23
Either you or Firefox 57 fixed it. I can't reproduce it anymore.

**Comment by samtstern** [comment] 2017-11-20 16:05
@d-schmidt thanks for the update!

**Comment by samtstern** [comment] 2017-11-20 16:05
Will add that to our internal investigation, closing this for now.

**Closed by samtstern** 2017-11-20 16:05 UTC

**Comment by krupalbhardiya** [comment] 2019-09-09 11:23
Having same issue on the dynamic links created.

Dynamic link Browser Support

Tested Browsers with link working:
Chrome
Firefox
Firefox lite
Opera
Samsung Internet Browser
Duck Duck Go
Jio Browser
Microsoft Edge
Maxthon Browser (MX5)
Phoenix Browser


Tested Browsers with link not working (User-Agent provided inside brackets):
- UC Browser mini
(Mozilla/5.0 (Linux; U; Android 8.1.0; en-US; Z50 Build/O11019) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 UCBrowser/12.11.9.1201 Mobile Safari/537.36)
- UC Browser (Mozilla/5.0 (Linux; U; Android 8.1.0; en-US; Z50 Build/O11019) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 UCBrowser/12.13.0.1207 Mobile Safari/537.36)
- Opera touch (Mozilla/5.0 (Linux; Android 9; ONEPLUS A5000 Build/PKQ1.180716.001) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Mobile Safari/537.36 OPT/1.21.76)
- Opera mini (Opera/9.80 (Android; Opera Mini/44.1.2254/151.113; U; en) Presto/2.12.423 Version/12.16)
- Firefox lite private browsing (Mozilla/5.0 (Linux; Android 8.1.0; Z50 Build/O11019; rv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Rocket/1.9.2(13715) Chrome/76.0.3809.132 Mobile Safari/537.36)
