### ISSUE TITLE
NullPointerException: Null reference used for synchronization

### ISSUE THREAD

**Issue by LiuDongCai** [firebase/quickstart-android#616] opened 2018-09-03 06:46 UTC
java.lang.NullPointerException: Null reference used for synchronization (monitor-enter)
	at android.os.Parcel.readException(Parcel.java:1706)
	at android.os.Parcel.readException(Parcel.java:1653)
	at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:4335)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:5779)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2382)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1532)
	at android.content.ContentResolver.query(ContentResolver.java:522)
	at android.content.ContentResolver.query(ContentResolver.java:479)
	at com.google.android.gms.internal.clearcut.zzy.zza(Unknown Source)
	at com.google.android.gms.internal.clearcut.zzy.zza(Unknown Source)
	at com.google.android.gms.internal.clearcut.zzae.zzb(Unknown Source)
	at com.google.android.gms.internal.clearcut.zzah.zzp(Unknown Source)
	at com.google.android.gms.internal.clearcut.zzae.zza(Unknown Source)
	at com.google.android.gms.internal.clearcut.zzae.zza(Unknown Source)
	at com.google.android.gms.internal.clearcut.zzae.zzl(Unknown Source)
	at com.google.android.gms.internal.clearcut.zzae.get(Unknown Source)
	at com.google.android.gms.internal.clearcut.zzp.zza(Unknown Source)
	at com.google.android.gms.clearcut.ClearcutLogger$LogEventBuilder.log(Unknown Source)
	at com.google.android.gms.internal.firebase-perf.zzh.zza(Unknown Source)
	at com.google.android.gms.internal.firebase-perf.zzh.zzb(Unknown Source)
	at com.google.android.gms.internal.firebase-perf.zzh.zza(Unknown Source)
	at com.google.android.gms.internal.firebase-perf.zzk.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

    implementation 'com.google.android.gms:play-services-base:15.0.1'
    implementation 'com.google.android.gms:play-services-maps:15.0.1'
    implementation 'com.google.android.gms:play-services-analytics:16.0.3'
    implementation 'com.google.firebase:firebase-core:16.0.3'
    implementation 'com.google.firebase:firebase-messaging:17.3.0'
    implementation 'com.google.firebase:firebase-perf:16.1.0'
    implementation 'com.google.android.gms:play-services-tagmanager:16.0.3'

phone: OPPO R11 
            7.1.1

**Comment by samtstern** [comment] 2018-09-13 21:07
Thanks @jkasnicki for jumping in.

@LiuDongCai we always appreciate your bug reports, but they generally seem to be just pasted stack traces. I assume you're getting them from Crashlytics or similar.

Without clear steps to reproduce (or at least a code snippet from your app that causes thre crash) there is nothing we can do to help you!

Closing this issue since it's been ~9 days since @jkasnicki asked a question and there's no more information, however if you can answer his questions I am happy to re-open and discuss.

**Closed by samtstern** 2018-09-13 21:07 UTC
