### ISSUE TITLE
Error: Local model load failed

### ISSUE THREAD

**Issue by yizhaoyanbo** [firebase/quickstart-android#836] opened 2019-03-15 02:40 UTC
### Step 1: Describe your environment

  * Android device: __Honor 9___
  * Android OS version: __8.0.0___
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

I my the custom model on android device, and load it from local . The program breaked at the following sentence.

return interpreter
                .run(inputs, dataOptions)
                .addOnFailureListener(new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {
                        Log.e(TAG, "Failed to get labels array: " + e.getMessage());
                        e.printStackTrace();
                    }
                })

  the detail  error info  is following:

cause = java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Didn't find op for builtin opcode 'SPLIT' version '3'
Registration failed.

detailMessage = Local model load failed: 

  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment] 2019-03-27 20:50
I think this is a duplicate of https://github.com/firebase/quickstart-android/issues/848

**Closed by samtstern** 2019-03-27 20:50 UTC
Labels: api: mlkit
