### ISSUE TITLE
FirebaseInstanceId

### ISSUE THREAD

**Issue by akrajilwar** [firebase/quickstart-android#72] opened 2016-07-02 17:21 UTC
E/FirebaseInstanceId: Error resolving target intent service, skipping classname enforcement. Resolved service was: akraj.snow.fcm/akraj.snow.fcm.MyFirebaseInstanceIDService

**Comment by ErstwhileWork** [comment] 2016-07-02 23:12
akrajilwar -- can you provide more information beyond just an error message?

**Comment by akrajilwar** [comment] 2016-07-03 04:34
firebase not generating token. I have two apps with fcm integrated. if i uninstall one app then second app working fine

**Comment by samtstern** [comment] 2016-07-06 21:55
Can you show the `AndroidManifest.xml` of each app?

**Comment by akrajilwar** [comment] 2016-07-07 07:05
1st app
`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.circleeduventures.app">

    <uses-feature android:name="android.hardware.camera" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CALL_PHONE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />

    <application
        android:name="com.circleeduventures.app.MyApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme">
        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id" />

        
        <activity
            android:name="com.circleeduventures.app.LoginActivity"
            android:configChanges="orientation|screenSize"
            android:label="@string/app_name"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.FullScreen">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        
        <activity
            android:name="com.circleeduventures.app.MainActivity"
            android:configChanges="orientation|screenSize"
            android:label="@string/app_name"
            android:screenOrientation="portrait">
        </activity>

        
        <activity
            android:name="com.circleeduventures.app.RegisterActivity"
            android:label="@string/title_activity_register"
            android:parentActivityName="com.circleeduventures.app.LoginActivity"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme">
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value="com.circleeduventures.app.LoginActivity" />
        </activity>

        
        <activity
            android:name="com.circleeduventures.app.widget.EmailVerify"
            android:label="@string/title_activity_email_verify"
            android:parentActivityName="com.circleeduventures.app.LoginActivity"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme">
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value="com.circleeduventures.app.LoginActivity" />
        </activity>

        
        <service android:name="com.circleeduventures.updater.UpdateService" />

        
        <activity android:name="com.facebook.FacebookActivity"
            android:configChanges=
                "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:theme="@android:style/Theme.Translucent.NoTitleBar"
            android:label="@string/app_name" />

        
        <activity
            android:name="com.facebook.CustomTabActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity>

        
        <service
            android:name=".gcm.CeduFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>

        <service
            android:name=".gcm.CeduFirebaseInstanceIDService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>


    </application>

</manifest>`

2nd app
`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="akraj.snow.fcm">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

    <application
        android:name=".MyApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".RegisterActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <service android:name=".MyFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <service android:name=".MyFirebaseInstanceIDService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>

        <activity
            android:name=".MainActivity"
            android:label="@string/title_activity_login">
        </activity>
    </application>

</manifest>`

**Comment by kmansoft** [comment] 2016-07-16 09:48
Same error message in the official GCM (not Firebase) sample from https://github.com/googlesamples/google-services/tree/master/android/gcm

The push messages are received just fine, and yet there are these in the logcat every time:

> FirebaseInstanceId  E  Failed to resolve target intent service, skipping classname enforcement
> E  Error while delivering the message: ServiceIntent not found.

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="gcm.play.android.samples.com.gcmquickstart">

    <!-- [START gcm_permission] -->
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <!-- [END gcm_permission] -->

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme">
        <activity
            android:name="gcm.play.android.samples.com.gcmquickstart.MainActivity"
            android:label="@string/app_name">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <!-- [START gcm_receiver] -->
        <receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND">
            <!-- Receive the actual message -->
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="gcm.play.android.samples.com.gcmquickstart" />
            </intent-filter>
            <!-- Receive the registration id -->
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="gcm.play.android.samples.com.gcmquickstart" />
            </intent-filter>
        </receiver>
        <!-- [END gcm_receiver] -->

        <!-- [START gcm_listener] -->
        <service
            android:name="gcm.play.android.samples.com.gcmquickstart.MyGcmListenerService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>
        <!-- [END gcm_listener] -->
        <!-- [START instanceId_listener] -->
        <service
            android:name="gcm.play.android.samples.com.gcmquickstart.MyInstanceIDListenerService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.gms.iid.InstanceID" />
            </intent-filter>
        </service>
        <!-- [END instanceId_listener] -->
        <service
            android:name="gcm.play.android.samples.com.gcmquickstart.RegistrationIntentService"
            android:exported="false"></service>
    </application>

</manifest>
```

**Comment by samtstern** [comment] 2016-07-18 15:30
@all after seeing a number of reports here with different symptoms I suspect that the error message about `classname enforcement` is spurious logging, but I am still looking into it.

**Comment by samtstern** [comment] 2016-07-19 16:57
@akrajilwar after circling back with the team it looks like you're experiencing a very rare (in our experience) Android framework bug.  That log message was added to detect this situation, but we have not been able to reliably reproduce it in a test scenario.

If you can reproduce this issue reliably, would you be open to sending a full `adb bugreport` to my email (samstern@google.com) so I can help the FCM folks debug this?  It would be valuable to use, but don't feel obligated since those bugreports do contain a lot of information.

**Comment by samtstern** [comment] 2016-07-25 22:24
@akrajilwar @kmansoft can either of you produce a bugreport of this happening?

**Comment by kmansoft** [comment] 2016-07-25 22:39
@samtstern Tried it again just now, not happening.

**Comment by jpaseneta** [comment] 2016-07-27 08:43
Hi,

i'm experiencing the same problem. as you can see, i'm receiving the messages after a downstream messaging using HTTP protocol(https://developers.google.com/cloud-messaging/downstream)

I've followed the original GCM setup thru here: https://developers.google.com/cloud-messaging/android/client

```
public void onMessageReceived(String from, Bundle data) {
        String title = data.getString("Title");
        String text = data.getString("Text");
        Log.d(TAG, data.toString());
        Log.d(TAG, "From: " + from);
        Log.d(TAG, "Message: " + title);
        //create notifications here.

        NotificationEngine.createBasicNotification(this,title,text,new Intent(this, DetailsActivity.class),R.drawable.ic_notiflogo);
        

    }
```

i'm using the IntentService context in my NotificationEngine to build NotificationCompat notifications, and along with that error, the notifications are not showing.

**Comment by sbsatter** [comment] 2016-07-29 17:09
I have mailed you @samtstern regarding this issue with the name of this thread as the subject of the mail.

**Comment by BurritoSmith** [comment] 2016-08-02 04:15
I'm seeing the same error on my application.  As others have said, the messages are received just fine in my GcmListenerService but it's a bit annoying to not see a clean logcat while I'm working.

I'm happy to send any logs if it'd help.  

I'm testing with a One Plus Two, and a Galaxy S7 Active...both have the errors....

**Comment by nvasilescu** [comment] 2016-08-15 15:33
I have the same error. It's good to see firebase brings soooo many new features to the table like this one.

**Comment by long-greg-c** [comment] 2016-08-16 10:42
@samtstern I have emailed you a adb bugreport of this issue occurring.

**Comment by samtstern** [comment] 2016-08-16 14:45
@long-greg-c thanks for the bugreport!

**Comment by samtstern** [comment] 2016-08-18 17:03
@long-greg-c can you reproduce this issue with the quickstart app provided in this repo or only with your own app that includes FCM?

**Comment by long-greg-c** [comment] 2016-08-19 09:07
@samtstern My own app is still using gcm. I have not tried to reproduce the issue with FCM using my own app or the quickstart app in this repo.

**Comment by sonjh1217** [comment] 2016-11-14 11:01
I was getting 
 E/FirebaseInstanceId: Failed to resolve target intent service, skipping classname enforcement
 E/FirebaseInstanceId: Error while delivering the message: ServiceIntent not found.

logs. But if I include "compile 'com.google.firebase:firebase-messaging:9.8.0'", I don't get these logs.
 I'm using GCM not FCM, and My code include "compile 'com.google.firebase:firebase-core:9.8.0'
    compile 'com.google.firebase:firebase-invites:9.8.0'" in gradle file. I searched for "firebaseInstanceId" in my project, and I found

 <application>

        <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
                <action android:name="com.google.android.c2dm.intent.REGISTRATION"/>
                <category android:name="${applicationId}"/>
            </intent-filter>
        </receiver>

        
        <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false"/>

        
        <service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
            <intent-filter android:priority="-500">
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>

    </application>
    
these lines in the generated AndroidManifest file. 
I can't understand why FirebaseInstanceId:  Failed to resolve target intent service log is getting triggered even though I'm not using FCM, and why these logs do not appear if I include the source "compile 'com.google.firebase:firebase-messaging:9.8.0".

**Comment by TasneemBohra** [comment] 2016-12-06 06:53
Why I am getting this error while implementing AppIndexing 

FirebaseInstanceId: Failed to resolve target intent service, skipping classname enforcement

**Comment by webmaster128** [comment] 2016-12-15 17:25
I can reliably reproduce the error on an Android 4.4 simulator:

```
E/FirebaseInstanceId: Failed to resolve target intent service, skipping classname enforcement
E/FirebaseInstanceId: Error while delivering the message: ServiceIntent not found.
```

The error occurs with `com.google.android.gms:play-services-gcm:9.6.1` as well as `com.google.android.gms:play-services-gcm:9.8.0`. We are not using any Firebase service, just plain old GCM. Push delivery works anyway.

I sent an `adb bugreport` to @samtstern, hope it helps.

**Comment by webmaster128** [comment] 2016-12-15 17:56
I it not reproducible anymore, but here is one observation: in every case the installed Play services were too old (`W/GooglePlayServicesUtil: Google Play services out of date.  Requires 9683000 but found 8489030`). Now I am not getting a new device token anymore so I don't think the server is still sending. But there was a time when the Google Play services where out of date (definitely, because it is the 4.4 simulator vs. play-services-gcm:9.6.1) and I did get notifications. Maybe I was able to use a very old device token.

**Comment by samtstern** [comment] 2016-12-15 18:07
@webmaster128 so if I understand your two comments correctly this issue only occurred when using a device with out of date google play services?

**Comment by webmaster128** [comment] 2016-12-15 18:10
Yes, and as far as I can see, utilizing an old device token. I just found a full log that I am examining right now and will send you soon.

**Comment by kmansoft** [comment] 2016-12-15 18:57
Re: old device tokens - this reminds me...

I've seen cases, after updating my app during debugging, where:

- The cloud server would get an "NotRegistered" from the GCM server
- And yet the app on the phone, if I forced a token refresh, would get same exact token ID value

So the two parts of GCM (the cloud server and Services on the device) would get out of sync wrt. the token.

Could the above be related?

**Comment by zahid--ali** [comment] 2016-12-29 06:36
Has anyone resolved this issue yet?

**Comment by samtstern** [comment] 2017-01-10 22:48
One situation where this may happen is if you are using **GCM** (not FCM) but using the `google-services` plugin to deal with the `google-services.json` file.  What happens is the `google-services` plugin brings in the `firebase-iid` library as a dependency.  If `firebase-iid` can't find your `FIrebaseMessagingService` it will log this error.  If you're only using GCM you can definitely ignore this.

So while we're still looking into this, for most cases this is a red herring.  If you're having issues getting your messages and seeing this log message the two are likely not related.  I'd ignore this message and see if there's another cause to your issues (likely contained in something like #4 or #89).

**Comment by kmansoft** [comment] 2017-01-11 19:08
@samtstern I'm not using google-services plugin or google-services.json.

**Comment by yayaa** [comment] 2017-01-31 15:15
Like @TasneemBohra i'm also using Firebase only for AppIndexing to personal content indexing specifically, and i saw these logs as well. I'd like to ignore, but still wanted to address here.

**Comment by samtstern** [comment] 2017-06-28 15:31
It's been a long time since the last update here so I am going to close this issue.  Thank you for reporting it and feel free to re-open if it you'd like to discuss further.

**Closed by samtstern** 2017-06-28 15:31 UTC

**Comment by zenyagami** [comment] 2017-08-28 14:23
This is happening again but only on Android 8.0 (not preview)

**Comment by jitendracodehacker** [comment] 2018-02-24 18:57
I am facing this on xamarin .

**Comment by tianxu0836** [comment] 2018-04-02 20:53
So is this problem only happens on GCM? 
If it is GCM, I can just ignore it, is it right?

**Comment by MaheshGawhane11** [comment] 2019-07-16 09:25
I am getting "FirebaseInstanceId: Error while delivering the message: ServiceIntent not found" when app is killed.
Its working fine on Foreground and Background.
#facing this issue from last few days. Same code working fine before.

**Comment by akrajilwar** [comment] 2019-07-19 11:58
Firebase Messaging Service is updated. you need to check docs. here is link [https://firebase.google.com/docs/cloud-messaging/android/client](Firebase Cloud Messaging)

**Comment by krunalshah-insigmainc** [comment] 2019-09-24 05:47
FirebaseInstanceId: Error while delivering the message: ServiceIntent not found.

This error we found when the application is in the background for a long time. This issue I found into Xaiomi devices. I tested into Samsung it's running perfectly but in Xaiomi, it always throwing an same error.
