### ISSUE TITLE
Request: show in crash sample how to add customized data as soon as the crash occurs

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [firebase/quickstart-android#541] opened 2018-06-18 13:22 UTC
I don't know if it's possible, but would be great to see how you suggest to add customized data that is most relevant in the time of the crash.

Currently, the only way to do this, that I know of, is by using setDefaultUncaughtExceptionHandler, as I did for Fabric Crashlytics :

        // init crashlytics:
        Fabric.with(application, new Crashlytics(), new Twitter(authConfig));
        // wrap the Crashlytics crash with on-time setting of data into its crash report : 
        Thread.setDefaultUncaughtExceptionHandler(new UncaughtExceptionHandler() {
            final UncaughtExceptionHandler defaultHandler = Thread.getDefaultUncaughtExceptionHandler();

            @Override
            public void uncaughtException(final Thread th, final Throwable ex) {
                Crashlytics.setString(...);
                defaultHandler.uncaughtException(th, ex);
            }
        });

But if there is a better way, please put it in the sample.

**Comment by TKBurner** [comment] 2018-06-18 20:15
Thanks! Check out this section in our docs :) https://firebase.google.com/docs/crashlytics/customize-crash-reports#add_custom_logs

**Comment by AndroidDeveloperLB** [comment] 2018-06-18 20:17
@TKBurner I'm talking about Android, and I'm talking about adding customized data, and I'm talking about doing it when the crash occurs.
What you provided is none of those.

**Comment by TKBurner** [comment] 2018-06-18 20:20
Please add this to your Android Manifest: 

`<meta-data android:name="firebase_crashlytics_collection_enabled" android:value="false" />`

after that you can invoke Crashlytics the same way you did with Fabric and everything will work exactly the way it did before.

**Comment by AndroidDeveloperLB** [comment] 2018-06-18 20:22
@TKBurner That's not what I asked about.
I asked if there is a nice API instead of the workaround I've presented here, and if so, show it in the sample.

**Comment by samtstern** [comment] 2018-06-18 20:23
@AndroidDeveloperLB just FYI that doc that @TKBurner linked tricked me too.  You have to scroll to the top and switch to the "Android" tab to see Android snippets.

**Comment by TKBurner** [comment] 2018-06-18 20:37
The sdks are actually the same right now and there will be a seamless
process to migrate from fabric to firebase in the near future.

**Comment by AndroidDeveloperLB** [comment] 2018-06-18 20:54
@TKBurner But will thing change? Will they stay the same? Will one stop being updated? What will happen?

**Comment by AndroidDeveloperLB** [comment] 2018-06-19 14:01
Is it worth switching to Firebase Crashlytics?
Will it at some point be better than Fabric? Maybe Fabric will be deprecated?

**Comment by samtstern** [comment] 2018-06-25 15:37
@AndroidDeveloperLB in many cases yes, it's worth switching.  Firebase Crashlytics should have all of the features you already love, plus some new integrations like integration with Cloud Functions or Google Analytics for Firebase.  I'd say give it a try and let us know what you think!

**Comment by samtstern** [comment] 2018-06-25 15:38
I am closing this issue, even though it was a good discussion, since I don't think we will change the quickstart to show this feature.  The quickstart is supposed to be as bare-bones as possible and this is an advanced feature.

**Closed by samtstern** 2018-06-25 15:37 UTC

**Comment by AndroidDeveloperLB** [comment] 2018-06-25 23:04
Can you please consider to add a second sample with this ? Or at least write about it in the docs as a tip?

**Comment by samtstern** [comment] 2018-06-26 20:59
@AndroidDeveloperLB I will see if we can add it to the docs, good idea!

**Comment by AndroidDeveloperLB** [comment] 2018-06-26 21:17
Thank you. Maybe let it be open then?

**Comment by samtstern** [comment] 2018-06-26 21:44
@AndroidDeveloperLB I try to keep open issues here limited to things that can be fixed within the repo (or where this is the best place to debug them).  Same reason I close issues here as soon as we find the root cause to be outside the sample, even if they are Firebase SDK issues.  Hope that makes sense!

**Comment by AndroidDeveloperLB** [comment] 2018-06-28 06:40
ok I hope you won't forget to add this tip somewhere.
