### ISSUE TITLE
Question: A/B testing +RemoteConfigs- how to track, and is cacheExpiration needed?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [firebase/quickstart-android#56] opened 2016-06-20 13:38 UTC
I can't find a sample or tutorial about how to track the current variant of the experiment.
For example, suppose we have 2 variants for the position of an button, and we wish to track how many people pressed the button on each variant. I'd also like to know where in the console website I need to see the stats.

I also don't understand the need for cacheExpiration when calling :

    mFirebaseRemoteConfig.fetch(cacheExpiration)

Is it really needed? Shouldn't there be an option that the cache will stay for as long as it can, perhaps removing it upon app-update? Or override it when there is new data from the server?

**Comment by kroikie** [comment] 2016-06-27 18:21
Given your button example, you would use Firebase Analytics to log events when users click on each variant of your button position. Then you can analyse the effectiveness of each button click via the Analytics UI in the Firebase console.

It is up to you when your application fetches new values from the server. If you only want to push new values upon an app-update then you would not need to fetch at all, you could set the default values in the app update and that version would just use the values defined in defaults. However if you do want your app to be able to fetch new values between app launches then you can call fetch whenever that seems reasonable given your application logic.

**Comment by AndroidDeveloperLB** [comment] 2016-06-28 15:17
Yes, I see.
Say, how come the "fetch" command sometimes freezes, not calling its
callback?
I've even reported about this here:
http://stackoverflow.com/questions/37994774/
This makes it unusable in many cases.

**Comment by kroikie** [comment] 2016-06-28 19:54
We have seen this issue reported and are currently investigating, I will update with a solution as soon as it is available.

**Comment by AndroidDeveloperLB** [comment] 2016-06-30 06:36
I see. I tried workaround of delaying the "fetch" call, but they didn't
work.
Please tell me when it gets fixed, because as long as we have this issue,
we can't really use Firebase in the app.

**Comment by kroikie** [comment] 2016-07-18 20:33
Update: This issue has been identified and we are currently working on a fix. I will update once a fix has been released.

**Comment by AndroidDeveloperLB** [comment] 2016-07-18 20:57
@kroikie Thank you.

**Comment by yoman07** [comment] 2016-08-01 09:39
@kroikie What is status for this problem?

**Comment by AndroidDeveloperLB** [comment] 2016-08-01 09:52
@yoman07 I've sent them a sample, but I didn't get any update about it. 
I hope it will get fixed soon.

**Comment by kroikie** [comment] 2016-08-03 18:36
Update: Apps built with the latest version of the Google Play services SDK (9.4) encounter this issue on fewer devices. A comprehensive fix to this issue is being developed and should be available soon. No changes were visible in the sample app because no changes are required in app code to implement this fix.

I will update once the comprehensive fix has been released.

**Comment by AndroidDeveloperLB** [comment] 2016-08-03 18:48
@kroikie Is there any workaround for this? And why does it occur? 
How come it was found only now? The SDK is out for a few months, and the issue even occurred on Nexus devices...

**Comment by kroikie** [comment] 2016-08-03 20:47
@AndroidDeveloperLB try delaying the call to fetch helps, say from onCreate to onResume. I have not been able to reproduce this on Nexus devices I have tried, which one have you seen this issue on? Given that the issue shows itself on some devices and not others it was difficult to track down. We have been able to reproduce it on one of our test devices and while Google Play services SDK 9.4 does improve things (less devices being affected) we should have a comprehensive fix out soon.

**Comment by AndroidDeveloperLB** [comment] 2016-08-03 21:08
I've already reported you guys about it on 9 devices and I don't remember how it went on each. I do remember that it doesn't always occur, and sometimes when I tried it over and over, it didn't occur.

About delaying, this didn't help.

**Comment by kroikie** [comment] 2016-08-03 23:49
@AndroidDeveloperLB you are still seeing this issue on SDK 9.4? If so could you indicate the devices here?

**Comment by AndroidDeveloperLB** [comment] 2016-08-04 08:36
@kroikie I don't work on Firebase for the time being, because of this issue, so I can't try it out on 9 devices (have other tasks at the office). It's also a bit rare to notice at the office.
If you work at Google, please have a look at the email sent to firebase-support@google.com , title has this number: "[9-0500000012256]" .
The email contains both a sample and information of which devices had this issue. 
I've tested now just on my device (Nexus 5x with Android 6.0.1) and it worked fine with 9.4 version of the sdk (on previous sdk version it got stuck), but I don't have time to test on others.

**Comment by AndroidDeveloperLB** [comment] 2016-08-04 08:42
Note that even though it seems that it worked on my device, it doesn't mean that it always works well.
I remember that for Nexus 4 with Android 5.1.1 , it used not to work, and after a few days, when trying it again, it worked fine (though quite slow - took ~5 seconds to get the variants etc...).

**Comment by AndroidDeveloperLB** [comment] 2016-08-04 11:40
I've not tested on Nexus 4 with 4.4.4, which had the issue before. It didn't occur this time. 
In order to be sure it got fixed I will need to try on all devices, and also try to reset Play-Store and/or Play-Services.

**Comment by kroikie** [comment] 2016-08-08 20:05
@AndroidDeveloperLB We have not been able to reproduce the issue on any of our devices with the new SDK I looked for your support case but that number did not seem to match your issue. Either way I will close this issue and feel free to open another one referring to this one if the issue is visible to you again.

**Closed by kroikie** 2016-08-08 20:05 UTC

**Comment by AndroidDeveloperLB** [comment] 2016-08-08 20:38
@kroikie  But you have succeeded seeing the issue on previous versions of Firebase, right?

**Comment by kroikie** [comment] 2016-08-08 21:25
Yes in versions previous to 9.4.0 we were able to reproduce the issue so now we are confident that it is very unlikely to occur and are working on another update that will make it impossible.

**Comment by AndroidDeveloperLB** [comment] 2016-08-09 13:16
@kroikie I don't understand. So on which version the issue is gone? On 9.4.0 (which is currently the latest one), or on newer one?
Is it safe to use it on 9.4.0 ?

**Comment by kroikie** [comment] 2016-08-10 22:48
@AndroidDeveloperLB you should not see the issue on 9.4.0 or later.

**Comment by AndroidDeveloperLB** [comment] 2016-08-11 07:10
@kroikie  OK, thank you.
Sadly, due to the slow handling of this issue (more than a month since I reported it), we won't use it in the near future.
I hope that by the time we try it all again, it will be more friendly for A/B testing, because currently it all seem like a huge workaround by using various Firebase components.

**Comment by kroikie** [comment] 2016-08-11 14:42
@AndroidDeveloperLB thanks for the feedback, we are working on making A/B testing easier, so I trust the next time you try config it will be more suited to your A/B testing needs.
