### ISSUE TITLE
Firebase dynamic link kill my app when i clicked home button for minimum app

### ISSUE THREAD

**Issue by vinhhongquang** [firebase/quickstart-android#675] opened 2018-09-19 10:11 UTC
* Android device: Asus_T00J
  * Android OS version: 4.4.2
  * Google Play Services version: 13.2.80
  * Firebase core version: 16.0.3
  * Firebase dynamic link version: 16.1.1

When i click share link for start new version my app (app hadn't already opened ), my app will start and run. When i click home button for minimum app, and i check in recently app. In here, my app was kill and i don't see my app in recently app. The next time, i enter my app and i click home button, it will occur. 

  1. Click Link Share for my app
  2. My App start and run
  3. Click Home Button for minimum app
  4. My App was kill and not have in recently tab.

  
#### Observed Results:

  My App was kill and not have in recently tab.
  
#### Expected Results:

 My App run in background.
  
#### Relevant Code:

Here is code for create Link Share: 

DynamicLink dynamicLink = FirebaseDynamicLinks.getInstance().
createDynamicLink().setLink(Uri.parse("https://www.google.com.vn/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjKxIT_6MbdAhWLp48KHeGzCDIQjRx6BAgBEAU&url=https%3A%2F%2Fwww.pexels.com%2Fsearch%2Fflowers%2F&psig=AOvVaw2KG8fLmXly11n2QuNSnH_K&ust=1537437995584138")).
setDynamicLinkDomain("dynamiclink12.page.link").
setAndroidParameters(new DynamicLink.AndroidParameters.Builder().build()).
setIosParameters(new DynamicLink.IosParameters.Builder("com.example.ios").build()).
buildDynamicLink();

And here code for receiver Link Share in function onCreate():

 FirebaseDynamicLinks.getInstance().getDynamicLink(getIntent()).
addOnSuccessListener(this, new OnSuccessListener<PendingDynamicLinkData>() {
            @Override
            public void onSuccess(PendingDynamicLinkData pendingDynamicLinkData) {
                if (pendingDynamicLinkData != null){
                    Toast.makeText(MainActivity.this, pendingDynamicLinkData.getLink().toString(), Toast.LENGTH_SHORT).show();
                }
            }
        });

**Comment by samtstern** [comment] 2018-09-19 22:33
I believe this is a duplicate of https://github.com/firebase/quickstart-android/issues/422

**Closed by samtstern** 2018-09-19 22:33 UTC
