### ISSUE TITLE
V/FirebaseCrash: Firebase Crash Reporting is disabled.

### ISSUE THREAD

**Issue by yokei15** [firebase/quickstart-android#14] opened 2016-05-23 11:49 UTC
HI, 
Im facing this type of issue,can you help me how to rectify, how to make enable firebase crash reporting.,this my error in logcat

V/FirebaseCrash: Firebase Crash Reporting is disabled.
E/FirebaseCrash: Failed to initialize crash reporting 
com.google.firebase.crash.internal.zzg$zza: com.google.android.gms.internal.zzqi$zza: No acceptable module found. Local version is 0 and remote version is 0.
at com.google.firebase.crash.internal.zzg.zzah(Unknown Source)
at com.google.firebase.crash.FirebaseCrash.<init>(Unknown Source)
at com.google.firebase.crash.FirebaseCrash.getInstance(Unknown Source)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
 at com.google.firebase.FirebaseApp.zza(Unknown Source)
 at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
at com.google.firebase.FirebaseApp.zzbu(Unknown Source)
 at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
at android.app.ActivityThread.installProvider(ActivityThread.java:4866)
at android.app.ActivityThread.installContentProviders(ActivityThread.java:4461)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4401)
at android.app.ActivityThread.access$1500(ActivityThread.java:139)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1270)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5097)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)
Caused by: com.google.android.gms.internal.zzqi$zza: No acceptable module found. Local version is 0 and remote version is 0.
 at com.google.android.gms.internal.zzqi.zza(Unknown Source)
  at com.google.firebase.crash.internal.zzg.zzah(Unknown Source) 
at com.google.firebase.crash.FirebaseCrash.<init>(Unknown Source) 
at com.google.firebase.crash.FirebaseCrash.getInstance(Unknown Source) 
 at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:515) 
at com.google.firebase.FirebaseApp.zza(Unknown Source) 
at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
at com.google.firebase.FirebaseApp.zzbu(Unknown Source) 
at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source) 
at android.content.ContentProvider.attachInfo(ContentProvider.java:1591) 
at android.content.ContentProvider.attachInfo(ContentProvider.java:1562) 
 at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source) 
at android.app.ActivityThread.installProvider(ActivityThread.java:4866) 
at android.app.ActivityThread.installContentProviders(ActivityThread.java:4461) 
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4401) 
  at android.app.ActivityThread.access$1500(ActivityThread.java:139) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1270) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:136) 
at android.app.ActivityThread.main(ActivityThread.java:5097) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:515) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
 at dalvik.system.NativeStart.main(Native Method) 
05-23 17:17:17.450 2462-2462/com.example.balaji.samplefirebase D/FirebaseApp: Initialized class com.google.firebase.crash.FirebaseCrash.
05-23 17:17:17.693 2462-2462/com.example.balaji.samplefirebase V/FirebaseCrash: Firebase Crash Reporting is disabled.
05-23 17:17:17.693 2462-2462/com.example.balaji.samplefirebase V/FirebaseCrash: Firebase Crash Reporting is disabled.
05-23 17:32:50.064 17461-17461/com.example.balaji.samplefirebase E/FirebaseCrash: Failed to initialize crash reporting
com.google.firebase.crash.internal.zzg$zza: com.google.android.gms.internal.zzqi$zza: No acceptable module found. Local version is 0 and remote version is 0.
 at com.google.firebase.crash.internal.zzg.zzah(Unknown Source)
 at com.google.firebase.crash.FirebaseCrash.<init>(Unknown Source)
at com.google.firebase.crash.FirebaseCrash.getInstance(Unknown Source)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.google.firebase.FirebaseApp.zza(Unknown Source)
at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
 at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
at com.google.firebase.FirebaseApp.zzbu(Unknown Source)
at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
 at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
at android.app.ActivityThread.installProvider(ActivityThread.java:4866)
 at android.app.ActivityThread.installContentProviders(ActivityThread.java:4461)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4401)
at android.app.ActivityThread.access$1500(ActivityThread.java:139)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1270)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5097)
 at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)
Caused by: com.google.android.gms.internal.zzqi$zza: 
No acceptable module found. Local version is 0 and remote version is 0.
 at com.google.android.gms.internal.zzqi.zza(Unknown Source)
 at com.google.firebase.crash.internal.zzg.zzah(Unknown Source) at com.google.firebase.crash.FirebaseCrash.<init>(Unknown Source) 
at com.google.firebase.crash.FirebaseCrash.getInstance(Unknown Source) 
 at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:515) 
at com.google.firebase.FirebaseApp.zza(Unknown Source) 
at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
at com.google.firebase.FirebaseApp.zzbu(Unknown Source) 
at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source) 
at android.content.ContentProvider.attachInfo(ContentProvider.java:1591) 
at android.content.ContentProvider.attachInfo(ContentProvider.java:1562) 
at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source) 
at android.app.ActivityThread.installProvider(ActivityThread.java:4866) 
at android.app.ActivityThread.installContentProviders(ActivityThread.java:4461) 
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4401) 
at android.app.ActivityThread.access$1500(ActivityThread.java:139) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1270) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:136) 
at android.app.ActivityThread.main(ActivityThread.java:5097) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:515) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
at dalvik.system.NativeStart.main(Native Method)

**Comment by samtstern** [comment] 2016-05-23 14:22
@yokei15 are you running on a device or emulator?  What is the version of Google Play Services on your device?

**Comment by yokei15** [comment] 2016-05-24 08:48
@samtstern Am running in Device... Play service version is 8.3.01

**Comment by samtstern** [comment] 2016-05-24 14:03
In that case this is the expected behavior. You will need play services
version 9.0.82 or higher.

**Comment by samtstern** [comment] 2016-05-24 17:01
Closing as intended behavior, if you can reproduce this on a device with Google Play Services >= 9.0.82 please re-open.

**Closed by samtstern** 2016-05-24 17:01 UTC

**Comment by yokei15** [comment] 2016-05-25 07:16
Thank you its working after updating Google play service @samtstern

**Comment by nilsi** [comment] 2016-07-27 05:12
I added the following to avoid crash in case the user does not have Google services installed.

```
//Check if google play services is up to date
final int playServicesStatus = GoogleApiAvailability.getInstance().isGooglePlayServicesAvailable(this);
if(playServicesStatus != ConnectionResult.SUCCESS){
    //If google play services in not available show an error dialog and return
    final Dialog errorDialog = GoogleApiAvailability.getInstance().getErrorDialog(this, playServicesStatus, 0, null);
    errorDialog.show();
    return;
}
```

**Comment by yutin1987** [comment] 2016-07-31 00:49
I have the same error, on 9.2.1.
```
        classpath 'com.android.tools.build:gradle:2.1.2'
        classpath 'com.google.gms:google-services:3.0.0'
```
and
```
    compile 'com.google.firebase:firebase-core:9.2.1'
    compile 'com.google.firebase:firebase-crash:9.2.1'
    compile 'com.google.android.gms:play-services:9.2.1'
```
and then add
`apply plugin: 'com.google.gms.google-services' `

run on Genymotion Samsung Galaxy S6 - 5.0.0

```
E/FirebaseCrash( 2487): Failed to initialize crash reporting
E/FirebaseCrash( 2487): com.google.firebase.crash.internal.zzg$zza: com.google.android.gms.internal.zzsj$zza: No acceptable module found. Local version is 0 and remote version is 0.
E/FirebaseCrash( 2487): 	at com.google.firebase.crash.internal.zzg.zzbq(Unknown Source)
E/FirebaseCrash( 2487): 	at com.google.firebase.crash.FirebaseCrash.<init>(Unknown Source)
E/FirebaseCrash( 2487): 	at com.google.firebase.crash.FirebaseCrash.getInstance(Unknown Source)
E/FirebaseCrash( 2487): 	at java.lang.reflect.Method.invoke(Native Method)
E/FirebaseCrash( 2487): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/FirebaseCrash( 2487): 	at com.google.firebase.FirebaseApp.zza(Unknown Source)
E/FirebaseCrash( 2487): 	at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
E/FirebaseCrash( 2487): 	at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
E/FirebaseCrash( 2487): 	at com.google.firebase.FirebaseApp.zzeh(Unknown Source)
E/FirebaseCrash( 2487): 	at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
E/FirebaseCrash( 2487): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1686)
E/FirebaseCrash( 2487): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1655)
E/FirebaseCrash( 2487): 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
E/FirebaseCrash( 2487): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4964)
E/FirebaseCrash( 2487): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4559)
E/FirebaseCrash( 2487): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4499)
E/FirebaseCrash( 2487): 	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
E/FirebaseCrash( 2487): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
E/FirebaseCrash( 2487): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/FirebaseCrash( 2487): 	at android.os.Looper.loop(Looper.java:135)
E/FirebaseCrash( 2487): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
E/FirebaseCrash( 2487): 	at java.lang.reflect.Method.invoke(Native Method)
E/FirebaseCrash( 2487): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/FirebaseCrash( 2487): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/FirebaseCrash( 2487): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
E/FirebaseCrash( 2487): Caused by: com.google.android.gms.internal.zzsj$zza: No acceptable module found. Local version is 0 and remote version is 0.
E/FirebaseCrash( 2487): 	at com.google.android.gms.internal.zzsj.zza(Unknown Source)
E/FirebaseCrash( 2487): 	... 25 more
I/FirebaseInitProvider( 2487): FirebaseApp initialization successful
D/FirebaseInstanceId( 2487): background sync failed: MISSING_INSTANCEID_SERVICE, retry in 10s
D/FirebaseInstanceId( 2487): background sync failed: MISSING_INSTANCEID_SERVICE, retry in 20s
```

**Comment by yutin1987** [comment] 2016-07-31 02:40
Sorry, It's worked. I miss https://github.com/codepath/android_guides/wiki/Genymotion-2.0-Emulators-with-Google-Play-support
