### ISSUE TITLE
Firebase signInWithCredential callback isn't being called

### ISSUE THREAD

**Issue by okq91** [firebase/quickstart-android#756] opened 2018-12-03 18:05 UTC
When try to signInWithCredential by twitter using email that's already registered with facebook or vice versa,
Neither onComplete nor onFailure is being called and no response from firebase.

Please note that One account per email address option is enabled.
It must return FirebaseAuthUserCollisionException in task response.

```java
FirebaseAuth.getInstance().signInWithCredential(credential)
                .addOnCompleteListener(task -> {
                    if (firebaseCompleteListener != null)
                        firebaseCompleteListener.onComplete(task, Constants.FACEBOOK);
                }).addOnFailureListener(new OnFailureListener() {
            @Override
            public void onFailure(@NonNull Exception e) {
                firebaseCompleteListener.onFailed(e.getMessage());
            }
        });
```

Android device: Any (tested on OnePlus3,samsung s6 and huawei)
Android OS version: Any
Google Play Services version: 12.0.1
Firebase/Play Services SDK version: 12.0.1

```
classpath 'com.google.gms:google-services:3.0.0'
classpath 'com.google.firebase:firebase-plugins:1.1.0'
```

**Comment by samtstern** [comment] 2018-12-06 18:00
`if (firebaseCompleteListener != null)`

Is it possible that your `firebaseCompleteListener` is `null` at that point?

**Comment by samtstern** [comment] 2018-12-17 19:41
@okq91 when you say it was working fine "in the past" what changed?  And how are you sure the methods are not being called?  Logs / debugging?

**Comment by okq91** [comment] 2018-12-17 21:06
@samtstern Nothing has changed in my code and i have checked logs, also when debugging breakpoints not being invoked

**Comment by samtstern** [comment] 2018-12-17 21:08
@okq91 so you changed nothing in your code (identical APK) and it just stopped firing?  What happens if you use the latest version of the Firebase Auth SDK (rather than `12.0.1`)?

**Comment by okq91** [comment] 2018-12-17 21:32
@samtstern Yes the identical APK and the same Firebase settings "One account per email address" is enabled, Even when i upgrade Firebase to latest version still not firing.
It must return result so i can tell the user that he can't use the same email address with different providers.

**Comment by samtstern** [comment] 2018-12-17 22:12
@okq91 are you able to reproduce this same issue using the sample `auth` app in this repo on those devices?  That would help me reproduce it.

**Comment by samtstern** [comment] 2020-05-20 19:26
@okq91 since it's been a very long time and we never got a simple reproduction I am going to close this issue.  I am sorry we couldn't get to a better resolution.  If you have more problems with Firebase Auth, feel free to open a new issue.

**Closed by samtstern** 2020-05-20 19:26 UTC
Labels: api: auth
