### ISSUE TITLE
Notification icon not visible when receiving a message in background state

### ISSUE THREAD

**Issue by emilpradeep** [firebase/quickstart-android#429] opened 2018-02-09 13:07 UTC
Device: One plus 5, moto z play
OS : Oreo
Google play services version : 11.8.0
Firebase messaging sdk version : 11.8.0

when app is in background, Notification icon specified in android manifest is not been shown in notification panel in Oreo. This works on all other android versions.

The issue is really easy to reproduce, the notification icon is displayed when app is in foreground but in background, the icon is not visible or is just blank. I am using custom data payload with notification type to trigger a push from server. This issue occurs only in version 11.8.0 and Oreo, so i downgraded to version 11.6.2 and the issue is not there.

Manifest.xml
`<meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_notification_white" />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/black" />`

will this be fixed in the next update?

**Comment by gokulkr535** [comment] 2018-02-12 15:36
Cannot receive notifications when application is killed state..kindly provide solutions to receive notification via fcm even app is in killed state

**Comment by samtstern** [comment] 2018-02-12 23:58
This is a duplicate of #418

**Closed by samtstern** 2018-02-12 23:58 UTC

**Comment by pradeep9201439460** [comment] 2019-12-26 07:17
notifications icon is not shown instead of notification icon the app icon is shown. And its is happen only when the application is killed state..kindly provide solutions.
