### ISSUE TITLE
App launched from firebase dynamic link disappears from recent apps

### ISSUE THREAD

**Issue by adhithyagnair** [firebase/quickstart-android#422] opened 2018-02-06 10:17 UTC
* Android device: Almost every device
  * Android OS version: L,M,N
  com.google.gms:google-services:3.1.0'
  classpath 'com.google.firebase:firebase-plugins:1.1.1'
  
It launches the app with no issues, but when I background the app, it disappears from the recent app

Steps to reproduce:

  1. Open app from dynamic link- no app instance should be in background
  2. minimize the newly open app
  3. move to some other app
  4. open recent apps tray- observed: no app instance of our app is present

Used the same sample in quickstart- android

**Comment by samtstern** [comment] 2018-02-07 20:36
@adhithyagnair where are you clicking on the dynamic link?  Web browser?  Email?  Another app?

Also can you provide a screenshot of what you see in recent apps?

**Comment by championboylay** [comment] 2018-02-14 07:15
Same happening to me! I opened the links via Viber application and my application is not listed in recent apps. Open application manually is working fine.

**Comment by samtstern** [comment] 2018-02-14 16:04
@championboylay can you show a screenshot of what your recent apps looks like after you click the link from Viber?

**Comment by adhithyagnair** [comment] 2018-02-21 05:58
![screenshot_20180221-112040](https://user-images.githubusercontent.com/30405024/36465114-b0d5014c-16f9-11e8-9ae0-93d74a97b23a.png)


@samtstern I was opening the app from Google-keep app and my deepLink app was not present in the background .
When I clicked the URL it opened my app as a new app instance-(as expected). then I switched between my app and other apps by clicking the highlighted button in screenshot. But by now My app istance gone missing :( .

**Comment by samtstern** [comment] 2018-02-21 21:29
Thanks @adhithyagnair, could you show your `AndroidManifest.xml`?

**Comment by adhithyagnair** [comment] 2018-02-22 05:29
` <?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.google.firebase.quickstart.deeplinks" >

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme" >
        <activity android:name=".MainActivity" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data
                    android:host="example.com"
                    android:scheme="https"/>
            </intent-filter>
            
        </activity>
    </application>

</manifest>
`

@samtstern  This is it. I just cloned this project.

**Comment by samtstern** [comment] 2018-02-23 16:47
@adhithyagnair huh ok that's very strange.  I will try and investigate this.

**Comment by samtstern** [comment] 2018-02-23 16:55
@adhithyagnair well you're totally right, I can reproduce this completely.  Let me go ask the engineering team if this is a bug or expected behavior.

**Comment by adhithyagnair** [comment] 2018-02-27 11:39
Oye, that's cool. Waiting for your further updates @samtstern . :)

**Comment by adhithyagnair** [comment] 2018-03-06 11:46
@samtstern Any updates?

**Comment by sree533** [comment] 2018-03-07 06:25
I have same issue!!

**Comment by jag4364u** [comment] 2018-03-07 06:28
I got a same problem. app opened using dynamic link is not in recent apps after minimising.

**Comment by samtstern** [comment] 2018-03-08 19:13
Hey all, I have been trying to get someone with more knowledge of the internals to chime in here.  Sorry for the silenve.

**Comment by William-ST** [comment] 2018-03-09 18:14
I got a same problem.

**Comment by guilhermekrz** [comment] 2018-03-21 19:15
Same with Android O. Is there any workaround?

**Comment by adhithyagnair** [comment] 2018-04-02 11:41
@samtstern Any updates on this?

**Comment by vishal-i4gs** [comment] 2018-04-10 06:40
Same issue, any fixes or workarounds ?

**Comment by sacot41** [comment] 2018-06-22 21:03
Same issue, someone have a update ?

**Comment by samtstern** [comment] 2018-06-22 21:31
I am closing this issue as there's nothing to do but wait.  Thanks again everyone for your help and patience.

**Closed by samtstern** 2018-06-22 21:31 UTC
Labels: dynamiclinks

**Comment by niczm25** [comment] 2018-07-24 07:21
<application
    android:allowBackup="true"
    android:icon="@mipmap/ic_launcher"
    android:label="@string/app_name"
    android:supportsRtl="true"
    android:theme="@style/AppTheme" >
    <activity android:name=".MainActivity" >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />

            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>

        
        <intent-filter>
            <action android:name="android.intent.action.VIEW"/>
            <category android:name="android.intent.category.DEFAULT"/>
            <category android:name="android.intent.category.BROWSABLE"/>
            <data
                android:host="example.com"
                android:scheme="https"/>
        </intent-filter>
        
    </activity>
</application>

I don't know if this the best possible answer, in the manifest file i remove <category android:name="android.intent.category.DEFAULT"/> from MainActivity, it works as expected, my question is there any side effect of what i did?

**Comment by vinhhongquang** [comment] 2018-10-15 03:52
I tested in Google play service version  14.3.66, it will fixed. But a lot of device use my app not receive this version 14.3.66 update, device only see newly version is 13.2.80 or 13.2.83. This cause my app not stable and have a bug. User use my app will anrgy. If firebase dynamic link haven't plan release or slient release for fix it, i think a lot of devive use my app will not compatibility.

**Comment by vinhhongquang** [comment] 2018-10-19 02:14
Someone have problem like me ?

**Comment by anusakha** [comment] 2018-10-28 11:54
G

**Comment by peterpeterpeter10101** [comment] 2018-10-28 12:00
passwords are problems now. too many ask in long in. need fixed, all
versions ( Google play service version 14.3.66, )  version 14.3.66 update,
device only see newly version is 13.2.80 or 13.2.83.  This cause my app not
stable and have a bug. User use my app will anrgy. If firebase dynamic link
