### ISSUE TITLE
Run

### ISSUE THREAD

**Issue by CynK88** [firebase/quickstart-android#1507] opened 2023-07-05 15:08 UTC
### Step 1: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by kroikie** [comment] 2023-07-05 15:37
@CynK88 I'm not sure what the issue is here, so I'll close this issue please open another one with more details if you still need help.

**Closed by kroikie** 2023-07-05 15:37 UTC
