### ISSUE TITLE
[Remote config] methods count increase

### ISSUE THREAD

**Issue by datnt1987** [firebase/quickstart-android#531] opened 2018-06-12 07:38 UTC
When adding firebase remote config, method count in my project increase over 1k methods. I just only use:

> import com.google.firebase.remoteconfig.FirebaseRemoteConfig;
> import com.google.firebase.remoteconfig.FirebaseRemoteConfigSettings;

Then methods increase again. So please help me how to proguard that to decrease them, the methods in my project just only have 812 methods left, and I don't user multidex support. Thanks in advance

P/S: Firebase remote config version 16.0.0

**Comment by datnt1987** [comment] 2018-06-12 08:50
when check dex-index-count tool, I found that remote config just only use 73 methods

> firebase: 755
>                 measurement_impl: 2
>                 messaging: 92
>                 provider: 9
>                 remoteconfig: 73

So I don't know why it increase over 1k4 methods when using.

My code looks like that

```
@Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        restarted = savedInstanceState != null;
        mLoginPresenter.attachView(this);
        mLoginPresenter.fetchAppResource();
        mLoginPresenter.handleIntent(getIntent());
        Timber.d("Init remote config");
        initRemoteConfig();
        Timber.d("Fetch remote config from server");
        fetchRemoteConfig();
    }

/*
    * Firebase functions for A/B testing
    * */
    private void initRemoteConfig() {
        // [START get_remote_config_instance]
        mFirebaseRemoteConfig = FirebaseRemoteConfig.getInstance();
        // [END get_remote_config_instance]

        // [START enable_dev_mode]
        FirebaseRemoteConfigSettings configSettings = new FirebaseRemoteConfigSettings.Builder()
                .setDeveloperModeEnabled(BuildConfig.DEBUG)
                .build();
        mFirebaseRemoteConfig.setConfigSettings(configSettings);
        // [START set_default_values]
        mFirebaseRemoteConfig.setDefaults(R.xml.remote_config_defaults);
        // [END set_default_values]
    }

    private void fetchRemoteConfig() {
//        long cacheExpiration = 3600; // 1 hour in seconds.
        long cacheExpiration = 0; // 1 hour in seconds.
        if (mFirebaseRemoteConfig.getInfo().getConfigSettings().isDeveloperModeEnabled()) {
            cacheExpiration = 0;
        }

        Executor executor = Executors.newSingleThreadExecutor();
        Task<Void> fetchTask = mFirebaseRemoteConfig.fetch(cacheExpiration);
        fetchTask.addOnCompleteListener(executor, this::onFetchRemoteConfigCompleted);
    }

    private void onFetchRemoteConfigCompleted(@NonNull Task<Void> task) {
        if (task.isSuccessful()) {
            Timber.d("Remote config: fetch remote config success");

            // After config data is successfully fetched, it must be activated before newly fetched
            // values are returned.
            mFirebaseRemoteConfig.activateFetched();

            Timber.d("Remote config: %s", mFirebaseRemoteConfig.getString("android_test"));
            Timber.d("Remote config: %s", FirebaseInstanceId.getInstance().getId());
        } else {
            Timber.d("Remote config: fetch remote config failed");
        }
    }

```

**Comment by samtstern** [comment] 2018-06-14 23:20
@datnt1987 unfortunately I don't think it's safe to remove the methods much further.  Remote Config relies on some common libraries in the `firebase` namespace. 

Could you explain why you can't use Multidex in your application?

**Comment by samtstern** [comment] 2018-06-25 15:32
Closing this issue as this is intended behavior, but I would still like to hear about why you don't want to use Multidex if you want to discuss it.

**Closed by samtstern** 2018-06-25 15:32 UTC

**Comment by datnt1987** [comment] 2018-06-29 08:12
Dear @samtstern ,
Sorry for lately reply your question. The reason why I don't want to use Multidex is my boss's request. He don't want to use Multidex and ask us try to code as less methods as possible. 

So, In this case, I used firebase 12.0.0 instead of using 16.0.0 for decrease the total methods to around 1k3.

Thanks so much for replying my question, Mr.

**Comment by samtstern** [comment] 2018-06-29 15:58
@datnt1987 thanks for the reply!  I would suggest:

- Use Multidex when debugging only.  If you have a device/emulator of API 21 or higher for testing you can use the native multidex and not even need to worry about any configuration.
- In production, if you turn on ProGuard (`minifyEnabled true`) it will cut out all the unused methods and you probably can stay in a single dex file.
