### ISSUE TITLE
Unknown intent action: com.google.firebase.MESSAGING_EVENT﻿

### ISSUE THREAD

**Issue by burhanshakir** [firebase/quickstart-android#299] opened 2017-07-11 10:26 UTC
Whenever I try to send a notification from the console using the registration token, I get this on my monitor : Unknown intent action: com.google.firebase.MESSAGING_EVENT﻿. What could be wrong ?

**Comment by kroikie** [comment] 2017-07-14 13:57
Hi, could you give a bit more information on how to reproduce this issue?
Where exactly are you seeing the message?

**Comment by vinod1988** [comment] 2017-07-16 10:34
I have the same issue.

 Unknown intent action: com.google.firebase.MESSAGING_EVENT

Any one resolved this

**Comment by burhanshakir** [comment] 2017-07-16 14:36
Seems like you have a issue in your gradle file. Maybe your Google play
services dependencies do not match with your firebase dependencies. Make
sure both the versions are same

**Comment by samtstern** [comment] 2017-08-11 01:21
Closing this issue due to lack of updates, unfortunately we need more information to debug.  Hope you got it all working in the end.

**Closed by samtstern** 2017-08-11 01:21 UTC

**Comment by haris15** [comment] 2017-12-19 07:46
check that your google play service version and firebase messaging library version is same

**Comment by dbwelch** [comment] 2019-10-31 16:02
Yes,have same issue, @haris15 not sure I understand "same version", they do not coordinate release levels for these libraries, how can they be "same"?
