### ISSUE TITLE
Firebase onVerificationCompleted not called Language Problem

### ISSUE THREAD

**Issue by dhruvkaushal11** [firebase/quickstart-android#794] opened 2019-01-27 09:47 UTC
Problem: Firebase Instant Auto Retrieval is not working on **SMS other than English** (Tested on Hindi)

Adittional Info: 
` implementation 'com.google.firebase:firebase-auth:16.0.5'

**Comment by samtstern** [comment] 2019-01-28 17:08
@dhruvkaushal11 are you saying that if you send the SMS to the same phone from the same app the auto-retrieval works if the SMS is in english but not in Hindi?  Or is this happening on different devices and you only suspect the language to be the cause.

In general please try to provide much more information when you file an issue, this is not enough to debug.

**Comment by dhruvkaushal11** [comment] 2019-01-31 09:13
@samedson Yes, I have also filled an issue regarding this at firebase support. **Issue No: 8-9184000024736**
Here is the video snap-shot for the same
https://drive.google.com/file/d/1GAvH_ZGCPs3-ft344zpuWuhe_743QEdr/view?usp=sharing

**Comment by samedson** [comment] 2019-01-31 14:44
@samtstern

**Comment by samtstern** [comment] 2019-01-31 16:02
@dhruvkaushal11 thanks for clarifying.  SMS issues like this are likely best handled through support so I will close this for now.  If you can't work it out with support let me know and we can re-open and discuss.

**Closed by samtstern** 2019-01-31 16:02 UTC
Labels: needs-attention
