### ISSUE TITLE
This app is not authorized to use Firebase Authentication. Please verifythat the correct package name and SHA-1 are configured in the Firebase Console.

### ISSUE THREAD

**Issue by ishandutta2007** [firebase/quickstart-android#355] opened 2017-10-15 04:26 UTC
Firebase auth was working fine, the debug build suddenly started failing without any change of code, logging the folloing message

> D/PhoneAuthActivity( 7392): signInWithCredential:failure:com.google.firebase.auth.FirebaseAuthException: This app is not authorized to use Firebase Authentication. Please verifythat the correct package name and SHA-1 are configured in the Firebase Console. [ App validation failed ].

The only notable activity inbetween a successful login and failure is android studio upgrade.

**Comment by samtstern** [comment] 2017-10-16 16:37
@ishandutta2007 the error message tells you exactly what is going on.  At some point in your "android studio upgrade" you likely deleted your android debug keystore which means your builds have a new SHA1 .  Just follow the steps to add your app to your Firebase project again and this should be fixed.

**Closed by samtstern** 2017-10-16 16:37 UTC

**Comment by ishandutta2007** [comment] 2017-10-17 10:57
solved [here](https://stackoverflow.com/questions/46751766/this-app-is-not-authorized-to-use-firebase-authentication-please-verify-that-the)

**Comment by alexandranb** [comment] 2018-11-27 14:52
Hi,

The solution mentioned above doesn't help me. Did it help you?

Thanks

**Comment by suniali** [comment] 2019-06-22 03:11
Hello,
This solution doesn't help me.

#err
Phone number verification failed. Code: firebaseAuth. Message: This app is not authorized to use Firebase Authentication. Please verifythat the correct package name and SHA-1 are configured in the Firebase Console. [ App validation failed ]

Note:I am using email authenticate and facebook auth right now and I don't have any problem.the problem is when I want use phone authenticate.

#flutter doctor
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.16299.1217], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.35.1)
[√] Connected device (1 available)

• No issues found!

**Comment by AsithaIndrajith** [comment] 2019-12-14 15:15
'./gradlew clean' -> inside root folder
Then re-buid the project

**Comment by braysonjohn148** [comment] 2020-03-13 15:23
I was using a Window computer, now i switched to Mac so i copied the whole app folder. But the problem is i get the error:


This app is not authorized to use Firebase Authentication. Please verify that the correct package name and SHA-1 are configured in the Firebase Console. [ App validation failed ]

I signed it also. i got the SHA-1 code and added to google.

   signingConfigs{
        release{
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

**Comment by Navayuvan-SB** [comment] 2020-04-13 05:59
Make sure you are running your app on a **Physical Device**. This error mostly occurs when you are running your app in an emulator.

**Comment by zuhairnaqi** [comment] 2020-05-07 11:04
Just open terminal enter this command `cd android && gradlew signingReport` you'll get multiple information in which copy  Task :app:signingReport >  debugUnitTest > SHA1 and add to firebase SHA certificate fingerprints.
After all re-build your app. Then it'll works.

**Comment by crsgarcias** [comment] 2021-03-15 06:19
Hi, someone was able to fix the error. I tried the following:

1. Get SHA1 from the debug keystore and add the firebase project settings.
2. Get SHA1 Released on Play App Signing
3. Link the application with the Play Console.

All those options didn't work for me, I removed the app and it didn't work either.

The login with Phone Number does not work, but the Facebook one does.

The first time I thought I had managed to fix the error, I tried it in Internal Tests and it worked fine, I uploaded it to production, and then it stopped working again.

I'm really desperate and I don't know what to do

**Comment by NatyN-teac** [comment] 2021-03-24 12:32
hey there guys, i m also experiencing the "this app is not authorized to use Firebase Authentication error" here is what i did, i have signed the application and add SHA-1 key of release(uploading key) to firebase, and also i have added google play key to firebase, even also i add the debug key also. but its keeps showing me that firebase auth is not  working for my OTP, But in debug mode when i run it from my android studio directly its working, when i build the apk and after i upload to play store its not working, any help would be appriciated ...

**Comment by adamGT** [comment] 2021-03-25 16:58
I've had this same issue for days. After trying every possible solution I found out my firebase-auth dependency version was (19.3.1) and when I change it to the latest i.e (20.0.3) it worked fine.
I hope this helps

**Comment by NatyN-teac** [comment] 2021-03-26 04:06
after one day of not working, then it starts working in both mode, but other issue came out when i upload the same apk i built for release to playstore it's not working but the same apk works when i install on my phone, i have done every possible configuration that might go wrong correctly.... can any one help on this

**Comment by aasif1297** [comment] 2021-05-23 06:48
> I was using a Window computer, now i switched to Mac so i copied the whole app folder. But the problem is i get the error:
> 
> This app is not authorized to use Firebase Authentication. Please verify that the correct package name and SHA-1 are configured in the Firebase Console. [ App validation failed ]
> 
> I signed it also. i got the SHA-1 code and added to google.
> 
> signingConfigs{
> release{
> keyAlias keystoreProperties['keyAlias']
> keyPassword keystoreProperties['keyPassword']
> storeFile file(keystoreProperties['storeFile'])
> storePassword keystoreProperties['storePassword']
> }
> }

Same issue. Got any solution?

**Comment by rohitsharma181589** [comment] 2021-06-23 16:21
I am also facing same issue, please suggest.

**Comment by aasif1297** [comment] 2021-06-23 16:25
> I am also facing same issue, please suggest.

I have just changed the these two lines in app build.gradle file and it worked. You can try this too.

classpath 'com.android.tools.build:gradle:3.5.0'
classpath 'com.google.gms:google-services:4.3.4'

**Comment by HrishikeshPator** [comment] 2021-07-31 06:03
> hey there guys, i m also experiencing the "this app is not authorized to use Firebase Authentication error" here is what i did, i have signed the application and add SHA-1 key of release(uploading key) to firebase, and also i have added google play key to firebase, even also i add the debug key also. but its keeps showing me that firebase auth is not working for my OTP, But in debug mode when i run it from my android studio directly its working, when i build the apk and after i upload to play store its not working, any help would be appriciated ...


Hey i'm facing the same issue... did you manage to solve it out?

**Comment by enriquejuan2** [comment] 2021-09-07 14:32
For me what i did was to update 

> 
> 
> > I am also facing same issue, please suggest.
> 
> I have just changed the these two lines in app build.gradle file and it worked. You can try this too.
> 
> classpath 'com.android.tools.build:gradle:3.5.0'
> classpath 'com.google.gms:google-services:4.3.4'

This worked for me, i also upgraded the authentication dependency.

**Comment by 5undaram900d** [comment] 2023-05-14 07:41
how to resolve this error in flutter firebase - error - This app is not authorized to use Firebase Authentication. Please verify that the correct package name, SHA-1, and SHA-256 are configured in the Firebase Console. [ Invalid request fields in play_integrity_token ]

**Comment by 5undaram900d** [comment] 2023-05-14 07:43
how to resolve this error in flutter firebase, Please help me quickly. I am adding all SHA-key but also this error happen for only phone authentication - 
error - This app is not authorized to use Firebase Authentication. Please verify that the correct package name, SHA-1, and SHA-256 are configured in the Firebase Console. [ Invalid request fields in play_integrity_token ]

**Comment by thatfiredev** [comment] 2023-05-15 09:42
@5undaram900d [this answer](https://stackoverflow.com/a/76149009/5861618) might help you. Make sure you get the SHA-256 from the Play console.

**Comment by smedic** [comment] 2023-05-23 10:57
I have this problem with Firebase BOM version 32.0.0. After I switched back to 31.0.0, problem disappeared. Pretty confusing.

**Comment by uv77** [comment] 2024-04-18 10:12
> Make sure you are running your app on a **Physical Device**. This error mostly occurs when you are running your app in an emulator.

I never thought about it till now , And it  Fucking worked . Thanks Maaan .
