### ISSUE TITLE
AppInviteApi leaking activity

### ISSUE THREAD

**Issue by idanakav** [firebase/quickstart-android#125] opened 2016-09-06 09:08 UTC
### Step 1: Are you in the right place?
- Memory leak can be easily reproduced in the app-invite sample on this repository
### Step 2: Describe your environment
- Android device: SM-N910C
- Android OS version: 6.0.1
- Google Play Services version: 9.4.52
- Firebase/Play Services SDK version: 9.4.0
### Step 3: Describe the problem:

The AppInviteApi seems to be leaking the activity passed as parameter to the getInvitation method
#### Steps to reproduce:
1. Start the app-invite sample
2. Kill the activity i.e by screen rotation
#### Observed Results:

By inspecting the heap dump you can see the the activity is leaked i.e from MAT:

```
com.google.android.gms.internal.zzmn$zze$1 @ 0x12f312a0 Native Stack
   -> bW com.google.android.gms.internal.zzmn$zze @ 0x12dd2420
      -> bT com.google.firebase.quickstart.invites.MainActivity @ 0x12d0bbc0
```

This is a heap dump that I took after few screen rotations and initiating GC from the Android Monitor,
using merge shortest path to GC root from MainActivity (excluding weak references)

Also i'm wondering why is the GC root referenced as Native Stack, any idea?

[Screenshot of MAT](https://drive.google.com/file/d/0B4xTmmg-i-shU083elNkMFpvaVk/view?usp=sharing)

[Heap dump](https://drive.google.com/open?id=0B4xTmmg-i-shYUxNbzBYbjZNN0E)
#### Expected Results:
- The activity not to be leaked
#### Relevant Code:

This is the code block causing the leak:

```
        AppInvite.AppInviteApi.getInvitation(mGoogleApiClient, this, autoLaunchDeepLink)
                .setResultCallback(
                        new ResultCallback<AppInviteInvitationResult>() {
                            @Override
                            public void onResult(AppInviteInvitationResult result) {
                                Log.d(TAG, "getInvitation:onResult:" + result.getStatus());
                                if (result.getStatus().isSuccess()) {
                                    // ...

                                }
                            }
                        });
    }

```

**Comment by greyski** [comment] 2016-10-14 22:48
Just to confirm, reproduced with this environment as well:

Android device: Nexus 6P
Android OS version: 7.0
Google Play Services version: 9.8.77
Firebase/Play Services SDK version: 9.4.0

Would be great if this was looked into as leaking an Activity is kind of a big issue and blocker for using this library.

**Comment by samtstern** [comment] 2016-10-17 19:00
Confirmed using LeakCanary, will investigate
![screenshot_20161017-115816](https://cloud.githubusercontent.com/assets/8466666/19451222/5341e7dc-9461-11e6-922a-e1b46f367112.png)

**Comment by samtstern** [comment] 2016-11-01 22:19
The AppInvites team is working on a fix for this, not sure when it will see release but just wanted to post this update and thank everyone who reported this.

**Comment by samtstern** [comment] 2016-11-16 17:40
Hey all.  I know it's been a while here but someone on the Invites team just told me about a workaround that will prevent this leak, and it's super simple.

Basically if you were doing this:
```java
        AppInvite.AppInviteApi.getInvitation(mGoogleApiClient, activity, true)
                .setResultCallback(new ResultCallback<AppInviteInvitationResult>() {
                     // ...
                });
```

You can do this to prevent the leak
```java
        Intent intent = this.getIntent();
        AppInvite.AppInviteApi.getInvitation(mGoogleApiClient, null, false)
                .setResultCallback(new ResultCallback<AppInviteInvitationResult>() {
                     // ...

                     // Launch the deep link (simulates passing "true" above)
                     startActivity(intent);
                });
```

**Comment by dsiddiqui489** [comment] 2016-11-21 21:27
@samtstern thanks for posting this work around! I had a few questions:

- we need to check for result == success before launching activity right? otherwise it'll launch this even for non-dynamic link cases.

- if we want to distinguish between normal intents and firebase dynamic link intents, do you think this code makes sense?

` AppInvite.AppInviteApi.getInvitation(mGoogleApiClient, null, false /* auto launch */);
   boolean isFirebaseLink = AppInviteReferral.hasReferral(intent);`

- It looks like Firebase will actually store all the deeplink information / key-value pairs before the user even installs or launches the app. So there will not be any network callbacks if the user were to launch the app on a fresh install via the App Invites API. Is this correct?

**Comment by samtstern** [comment] 2016-11-21 21:32
@dsiddiqui489 yep I think you have the right idea on all points, although when/how the API accesses the network should be considered a black box and may change over time (but you're right for now).

**Comment by dsiddiqui489** [comment] 2016-11-21 21:33
Awesome, thanks!

**Comment by SUPERCILEX** [comment] 2016-12-24 01:16
@samtstern Thanks for the fix and explanation!

**Comment by samtstern** [comment] 2017-01-09 18:28
Doing some issue cleanup here.  As a fix is coming and the workaround is listed here, I am going to mark this issue as 'closed' since it no longer indicates any problem with the quickstart.  Thanks to all who helped find this!

**Closed by samtstern** 2017-01-09 18:28 UTC

**Comment by SUPERCILEX** [comment] 2017-02-22 02:13
@samtstern This is still an issue in `v10.2.0`:

```
In com.supercilex.robotscouter.debug:1.0.0-DEBUG:1.
* com.supercilex.robotscouter.ui.teamlist.TeamListActivity has leaked:
* GC ROOT com.google.android.gms.internal.zzum$zze$1.zzaip (anonymous subclass of com.google.android.gms.internal.zzum$zza)
* references com.google.android.gms.internal.zzum$zze.zzaim
* leaks com.supercilex.robotscouter.ui.teamlist.TeamListActivity instance

* Retaining: 71 KB.
* Reference Key: 8cd18ea9-b253-4b0e-bcdd-6c64f030f955
* Device: Google google Pixel XL marlin
* Android Version: 7.1.2 API: 25 LeakCanary: 1.5 00f37f5
* Durations: watch=5265ms, gc=135ms, heap dump=5182ms, analysis=108007ms

* Details:
* Instance of com.google.android.gms.internal.zzum$zze$1
|   static $classOverhead = byte[248]@314751105 (0x12c2b881)
|   zzaip = com.google.android.gms.internal.zzum$zze@317562000 (0x12ed9c90)
|   mDescriptor = java.lang.String@315453792 (0x12cd7160)
|   mObject = 527624561552
|   mOwner = com.google.android.gms.internal.zzum$zze$1@317546368 (0x12ed5f80)
|   shadow$_klass_ = com.google.android.gms.internal.zzum$zze$1
|   shadow$_monitor_ = 0
* Instance of com.google.android.gms.internal.zzum$zze
|   static $classOverhead = byte[312]@317725825 (0x12f01c81)
|   zzaim = com.supercilex.robotscouter.ui.teamlist.TeamListActivity@316965696 (0x12e48340)
|   zzain = false
|   zzaio = android.content.Intent@315370288 (0x12cc2b30)
|   zzaxf = com.google.android.gms.common.api.Api@318181728 (0x12f71160)
|   zzazY = com.google.android.gms.common.api.Api$zzf@315381440 (0x12cc56c0)
|   zzK = false
|   zzaAh = java.lang.Object@315381512 (0x12cc5708)
|   zzaAi = com.google.android.gms.internal.zzaaf$zza@318182656 (0x12f71500)
|   zzaAj = java.lang.ref.WeakReference@318248248 (0x12f81538)
|   zzaAk = java.util.ArrayList@318248224 (0x12f81520)
|   zzaAl = null
|   zzaAm = java.util.concurrent.atomic.AtomicReference@318227136 (0x12f7c2c0)
|   zzaAn = null
|   zzaAo = true
|   zzaAp = false
|   zzaAq = null
|   zzaAr = null
|   zzaAs = false
|   zzair = com.google.android.gms.common.api.Status@316321408 (0x12daae80)
|   zzazt = null
|   zztj = java.util.concurrent.CountDownLatch@318227120 (0x12f7c2b0)
|   shadow$_klass_ = com.google.android.gms.internal.zzum$zze
|   shadow$_monitor_ = -2139240503
* Instance of TeamListActivity
[...]
* Excluded Refs:
| Field: android.view.Choreographer$FrameDisplayEventReceiver.mMessageQueue (always)
| Thread:FinalizerWatchdogDaemon (always)
| Thread:main (always)
| Thread:LeakCanary-Heap-Dump (always)
| Class:java.lang.ref.WeakReference (always)
| Class:java.lang.ref.SoftReference (always)
| Class:java.lang.ref.PhantomReference (always)
| Class:java.lang.ref.Finalizer (always)
| Class:java.lang.ref.FinalizerReference (always)
```

**Comment by AAverin** [comment] 2017-03-12 15:21
Confirming, issue is still there. Will try the workaround

**Comment by mobiRic** [comment] 2017-04-25 12:34
still broken on v10.2.1

**Comment by emarc-m** [comment] 2017-05-25 07:16
Still occurs in v10.2.6
