### ISSUE TITLE
Email not appearing for FirebaseUser when used with GoogleSigninActivity

### ISSUE THREAD

**Issue by nycodes9** [firebase/quickstart-android#13] opened 2016-05-23 07:11 UTC
This may have been inherited from FirebseAuth, when logging in with Google account the firebase user email is empty/null.
Seems we have to manually update email whereas photo Url is seamlessly picked up by firebase user !

Till few days ago (com.firebase) when users were added with google sign-in, email was added automatically as seen on users console.

**Comment by samtstern** [comment] 2016-05-23 15:49
@nycodes9 can you try the following steps:

  * Uninstall the app
  * Re-install the app
  * Go directly to GoogleSignInActivity
  * Sign in

Is the email still null in that case?

**Comment by morphine9** [comment] 2016-05-23 16:55
Yes tried all variations - with no different outcome.

**Comment by samtstern** [comment] 2016-05-24 00:22
@nycodes9 @morphine9 are you requesting email in your `GoogleSignInOptions`?

@iainmcgin do you know of a situation where email would be null from Google Sign In?

**Comment by morphine9** [comment] 2016-05-25 09:48
`GoogleSignInOptions gso = new GoogleSignInOptions.Builder(
                GoogleSignInOptions.DEFAULT_SIGN_IN)
                .requestIdToken(getString(R.string.default_web_client_id))
                .requestEmail()
                .requestProfile()
                .build();`

**Comment by samtstern** [comment] 2016-05-26 16:41
Ok those are the correct GoogleSignInOptions.  Does this happen when you use a different google account to sign in?

**Comment by morphine9** [comment] 2016-05-31 06:37
Same google a/c with which I'm registered with firebase.

**Comment by samtstern** [comment] 2016-05-31 18:42
@morphine9 can you capture the output of `adb logcat` during a sign-in attempt and upload it here?  If it's large you can use a pastebin or similar.

**Comment by ptornhult** [comment] 2016-05-31 20:58
This might be related:
In Firebase console under Auth -> Sign in method -> Advanced there is an option called "One account per email address". If this is Not checked (seems to have been the default), the users emails will be blanked when they sign in. 

I checked this option, removed my users and logged them in again and the email is now there in both console and client.

**Comment by samtstern** [comment] 2016-06-02 16:18
@ptornhult I have reproduced the behavior you just described, thanks for the tip!  This is surprising to me, but I will check with the authentication team to see if this is the expected behavior.

**Comment by samtstern** [comment] 2016-06-02 20:45
@ptornhult I have confirmed this is the intended behavior when you have multiple users per email address enabled.  We will be updating documentation to make this clearer so we have fewer surprised developers.

**Comment by samtstern** [comment] 2016-06-02 20:45
@nycodes9 I believe the information above should answer your question, closing this issue.  If you think there is a different cause to your problem, please reply and I will re-open.

**Closed by samtstern** 2016-06-02 20:46 UTC

**Comment by xsorifc28** [comment] 2016-09-21 17:34
@ptornhult Great find! Thank you.

**Comment by abhisheksoni27** [comment] 2020-06-28 12:25
How are we supposed to link the accounts using firebase admin sdk, if we do need to allow multiple accounts using same email address (and different social providers) ?

**Comment by lawloretienne** [comment] 2020-07-27 15:35
> This might be related:
> In Firebase console under Auth -> Sign in method -> Advanced there is an option called "One account per email address". If this is Not checked (seems to have been the default), the users emails will be blanked when they sign in.
> 
> I checked this option, removed my users and logged them in again and the email is now there in both console and client.

this still doesn't work for me even after this suggestion. the email field is still null.
