### ISSUE TITLE
java.lang.RuntimeException: Failed to instantiate module class: com.google.firebase.database.connection.idl.IPersistentConnectionImpl

### ISSUE THREAD

**Issue by tangjingyuan** [firebase/quickstart-android#123] opened 2016-09-06 07:32 UTC
Hi:
A user in our App always get crash. The log shows that it caused by firebase. Can anyone help me to solve it? Thank you.

Here is the crash log:

java.lang.RuntimeException: com.google.android.gms.internal.zzqi$zza: Failed to instantiate module class: com.google.firebase.database.connection.idl.IPersistentConnectionImpl
at com.google.firebase.database.connection.idl.IPersistentConnectionImpl.loadDynamic(Unknown Source)
at com.google.firebase.database.connection.idl.zzc.a(Unknown Source)
at com.google.android.gms.internal.zzadp.zza(Unknown Source)
at com.google.android.gms.internal.zzaeu.zza(Unknown Source)
at com.google.android.gms.internal.zzafc.<init>(Unknown Source)
at com.google.android.gms.internal.zzafe.zzb(Unknown Source)
at com.google.android.gms.internal.zzafe.zza(Unknown Source)
at com.google.firebase.database.h.e(Unknown Source)
at com.google.firebase.database.h.a(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by: com.google.android.gms.internal.zzqi$zza: Failed to instantiate module class: com.google.firebase.database.connection.idl.IPersistentConnectionImpl
at com.google.android.gms.internal.zzqi.zzdM(Unknown Source)
... 18 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.database.connection.idl.IPersistentConnectionImpl" on path: DexPathList[[zip file "/data/app/com.1/base.apk"],nativeLibraryDirectories=[/data/app/com.1/lib/arm, /data/app/com.-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
... 19 more
Suppressed: java.lang.ClassNotFoundException: com.google.firebase.database.connection.idl.IPersistentConnectionImpl
at java.lang.Class.classForName(Native Method)
at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
... 20 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

deviceType: GT-I9300

Google play services version: 9.2.56(246-124593566)

firebase version: 9.0.0

**Comment by samtstern** [comment] 2016-09-06 16:01
@tangjingyuan can you reproduce this crash or is it something you are seeing in your crash reporting dashboard only?

**Comment by tangjingyuan** [comment] 2016-09-07 02:34
@samtstern I cannot reproduce this crash. A user of our app report it to us.

**Comment by tangjingyuan** [comment] 2016-09-14 06:37
The user upgrade his google play version from 9.2.56 to 9.6.80. Now it works well ...

**Comment by samtstern** [comment] 2016-09-14 15:12
@tangjingyuan thanks for following up.  Since it's now working for your user and I can't reproduce it still, I am going to close this issue.

Please re-open if you see it again.

**Closed by samtstern** 2016-09-14 15:12 UTC
