### ISSUE TITLE
FirebaseAuth.signInWithEmailAndPassword internal NullPointerException

### ISSUE THREAD

**Issue by crazyhatfish** [firebase/quickstart-android#425] opened 2018-02-08 00:10 UTC
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
    * If you are filing an issue about **FCM in the background** make sure to read [#4](https://github.com/firebase/quickstart-android/issues/4) and [#89](https://github.com/firebase/quickstart-android/issues/89) first!
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: hudl 2
  * Android OS version: 4.4.2
  * Google Play Services version: unknown
  * Firebase Auth SDK version: 11.8.0
  
### Step 3: Describe the problem:

I'm getting a `NullPointerException` from a crash report when the user logs in. So far the only affected OS version is 4.4.2. API versions > 20 log in correctly.

```
com.google.android.gms.internal.zzdvv.zzb (Unknown Source)
com.google.android.gms.internal.zzdwc.zzb (Unknown Source)
com.google.firebase.auth.FirebaseAuth.signInWithEmailAndPassword (Unknown Source)
>>> com.mypackage.UserManager.login
```

```
com.google.android.gms.internal.zzdvv.zzb (Unknown Source)
com.google.android.gms.internal.zzdwc.zza (Unknown Source)
com.google.firebase.auth.FirebaseAuth.createUserWithEmailAndPassword (Unknown Source)
>>> com.mypackage.UserManager.register
```

**Comment by samtstern** [comment] 2018-02-08 00:45
@crazyhatfish can you show some of the code you are running that produces this exception?

**Comment by crazyhatfish** [comment] 2018-02-08 09:31
Sure, I forgot to mention that it occurs when registering and logging in.

```
this.auth.signInWithEmailAndPassword(items.getString(0), items.getString(1))
                        .addOnCompleteListener(new OnCompleteListener<AuthResult>() {
                            @Override
                            public void onComplete(@NonNull Task<AuthResult> task) {
                                resultCallback.invoke(task.isSuccessful());
                            }
                        });
```

The code that calls `createUserWithEmailAndPassword` is identical to this.

**Comment by samtstern** [comment] 2018-02-08 16:06
@crazyhatfish could you:

  * Show some more of the crash logs (more is better)
  * Provide more information about `items` and `resultCallback`.

Right now my only guess is that `resultCallback` could be `null` when the task completes.  If you us the forma `.addOnCompleteListener(this, listener)` when adding the listener it will be automatically removed at the end of the Activity lifecycle, which could help.

**Comment by samtstern** [comment] 2018-02-27 21:28
@crazyhatfish since there hasn't been a response in 19 days I assume you figured this out?  If not let me know and we can re-open this.

**Comment by crazyhatfish** [comment] 2018-03-04 21:38
Apologies, I've been waylaid on another project at work.

That's as high as the callstack as it goes, the rest of the error log (its a crashlytic error log) is pretty uninformative, although I may be wrong.
The full stack is as follows:
```
com.google.android.gms.internal.zzdvv.zzb (Unknown Source)
com.google.android.gms.internal.zzdwc.zzb (Unknown Source)
com.google.firebase.auth.FirebaseAuth.signInWithEmailAndPassword (Unknown Source)
com.mypackage.UserManager.login (UserManager.java:118)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:374)
com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:162)
com.facebook.react.bridge.queue.NativeRunnable.run (NativeRunnable.java)
android.os.Handler.handleCallback (Handler.java:733)
android.os.Handler.dispatchMessage (Handler.java:95)
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:31)
android.os.Looper.loop (Looper.java:149)
com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run (MessageQueueThreadImpl.java:194)
java.lang.Thread.run (Thread.java:841)
```

- `items` is a `ReadableArray` passed in from React Native JS
- `resultCallback` is a React Native `Callback`

I've verified that `items`, the `getString` return values and `resultCallback` are not `null` and it doesn't even get to the callback on an emulated Nexus 10 API 16.

**Comment by samtstern** [comment] 2018-03-05 17:30
@crazyhatfish thanks for getting back to me.  So if I understand correctly this is an issue in a React Native app only affecting users on KitKat and below.

I will leave this open for now, but as you noted there's not much information here and it doesn't seem that either of us can reproduce this too easily so I'm not quite sure how to proceed with debugging ... I'll see if I can do anything with those logs.

**Comment by samtstern** [comment] 2018-03-05 18:13
Fwiw I looked into the proguard mapping and all I can see about `zzdvv` and `zzdwc` are that they are inside the operations you specified, so it's very hard to figure out where the NPE is coming from.

**Comment by crazyhatfish** [comment] 2018-03-06 01:04
Thanks for looking at this for me.

Here is a minimal app reproducing the crash: [tmpapp.tar.gz](https://github.com/firebase/quickstart-android/files/1783136/tmpapp.tar.gz)
Ran on an emulated Nexus 10 API 16, stock image.

It's a React Native app, wasn't sure if that was a contributing factor. Should be just a `npm i`, `npm start` to get it running.

**Comment by samtstern** [comment] 2018-03-08 21:40
@crazyhatfish ok I was able to reproduce this on an API 16 emulator.

**Comment by samtstern** [comment] 2018-03-08 21:49
@crazyhatfish ok I installed a newer version of Google Play services on the emulator and this did **not** crash anymore (see below).  The API 16 emulator came with a version old version (9.x) and there must be some binary incompatibility between the new SDK and that one.

Because the emulator does not have the play store, there's no way for these devices to upgrade Google Play services which causes the crash.

So I would guess that your users have a very old version of Google Play services, or are running on a device that was never meant to have Google Play services.

While Firebase Auth normally does these checks for you, there must be something strange going on on these devices.  The best I can offer you is the `GoogleApiAvailability` class which would allow you to make some of these checks in your app code and possibly warn the user that their device is not compatible:
https://developers.google.com/android/reference/com/google/android/gms/common/GoogleApiAvailability.html#isGooglePlayServicesAvailable(android.content.Context)

<img width="382" alt="android_emulator_-_nexus_s_api_16_google__5554" src="https://user-images.githubusercontent.com/8466666/37178373-1fde3a16-22d7-11e8-80e4-1dd044183986.png">

**Comment by samtstern** [comment] 2018-03-08 21:49
Gonna report this as a bug, but closing it here since there's nothing more I can do :-/

**Closed by samtstern** 2018-03-08 21:49 UTC

**Comment by crazyhatfish** [comment] 2018-03-08 22:38
Awesome, that's perfect :100:. Cheers
