### ISSUE TITLE
Apk firebase-*.properties Files

### ISSUE THREAD

**Issue by iiShadow** [firebase/quickstart-android#671] opened 2018-09-17 04:38 UTC
### Step 1: APK Analyzer firebase.properties Files? How to remove it？

![image](https://user-images.githubusercontent.com/6167082/45606228-e7efea00-ba75-11e8-8dde-5bee07aac9fe.png)
 

### Step 2: 

  * Android device: Xiaomi
  * Android OS version: 8.1.0
  * Google Play Services version: 15.0.1
  * Firebase/Play Services SDK version: 16.0.1

**Comment by samtstern** [comment] 2018-09-18 16:12
@iiShadow are these `.properties` files causing a problem for you?  They just contain the SDK `version` and are extremely small (<100B) so they should not bloat your app or affect anything at runtime.

**Comment by samtstern** [comment] 2018-10-02 15:33
There hasn't been a response in 2 weeks and I think this is intended behavior, so closing the issue.

**Closed by samtstern** 2018-10-02 15:33 UTC

**Comment by Thomas-Vos** [comment] 2020-06-17 20:07
Why are these `.properties` files needed, what are they used for?
